'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {UserRound,ShieldCheck,SlidersHorizontal,Database,ArrowUpRight,CheckCircle2,AlertCircle,LoaderCircle,Eye,EyeOff,Download,LogOut,Trash2,Bookmark,FileText,FolderOpen,Mail} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {updateUser,getUser,changePassword,deleteAccount,logout} from '@/lib/auth-client';
import {request} from '@/lib/api-client';
import {AccountPreferences} from './account-preferences';
import './account-dashboard.css';
type User={id:string;email:string;name?:string;emailVerified?:boolean};
type Feedback={kind:'success'|'error';message:string}|null;
function PasswordField({label,name,minLength}:{label:string;name:string;minLength?:number}){
 const [show,setShow]=useState(false);
 return <div className="field"><label htmlFor={'account-'+name}>{label}</label><div className="account-password"><input id={'account-'+name} name={name} type={show?'text':'password'} required minLength={minLength} maxLength={128} autoComplete={name==='current'?'current-password':'new-password'}/><button type="button" aria-label={(show?'Hide ':'Show ')+label.toLowerCase()} aria-pressed={show} onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>;
}
export function AccountPanel({user,onUpdate}:{user:User;onUpdate:(user:User)=>void}){
 const [name,setName]=useState(user.name||''),[busy,setBusy]=useState(''),[feedback,setFeedback]=useState<Feedback>(null),[deleting,setDeleting]=useState(false),[deletePassword,setDeletePassword]=useState(''),[confirmation,setConfirmation]=useState('');
 const lock=useRef(false),deleteForm=useRef<HTMLFormElement>(null);
 useEffect(()=>{setName(user.name||'')},[user.name]);
 const changed=name.trim()!==(user.name||'');
 async function run(action:string,fn:()=>Promise<string|void>){if(lock.current)return;lock.current=true;setBusy(action);setFeedback(null);try{const message=await fn();if(message)setFeedback({kind:'success',message})}catch(e){setFeedback({kind:'error',message:e instanceof Error?e.message:'We could not complete the request. Please try again.'})}finally{lock.current=false;setBusy('')}}
 async function exportData(){await run('export',async()=>{const response=await request('/api/export');if(!response.ok)throw Error('Your export could not be prepared. Please try again.');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='VortexPlots_Account_Export_'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);return 'Your account export is ready and the download has started.'})}
 const initials=(user.name||user.email).split(/\s+/).slice(0,2).map(s=>s[0]).join('').toUpperCase();
 return <div className="account-studio">
  <section className="account-hero"><div className="account-avatar" aria-hidden="true">{initials}</div><div className="account-identity"><p className="account-eyebrow">YOUR PERSONAL WORKSPACE</p><h2>{user.name||'Your account'}</h2><p><Mail size={14}/>{user.email}</p></div><span className={'account-badge '+(user.emailVerified?'verified':'pending')}><ShieldCheck size={15}/>{user.emailVerified?'Email verified':'Email not verified'}</span></section>
  <div className="account-feedback-slot" aria-live="polite" aria-atomic="true">{feedback&&<div className={'account-feedback '+feedback.kind}>{feedback.kind==='success'?<CheckCircle2 size={18}/>:<AlertCircle size={18}/>}<span>{feedback.message}</span><button type="button" aria-label="Dismiss account message" onClick={()=>setFeedback(null)}>×</button></div>}</div>
  <div className="account-layout"><Tabs defaultValue="profile" className="account-tabs"><TabsList className="account-tab-list" aria-label="Account settings">{[['profile','Profile',UserRound],['security','Security',ShieldCheck],['preferences','Preferences',SlidersHorizontal],['privacy','Data & privacy',Database]].map(([value,label,Icon])=>{const Glyph=Icon as typeof UserRound;return <TabsTrigger key={String(value)} value={String(value)}><Glyph size={17}/><span>{String(label)}</span></TabsTrigger>})}</TabsList>
   <TabsContent value="profile" forceMount className="account-tab-panel"><section className="account-card"><header><span className="account-card-icon"><UserRound size={21}/></span><div><h2>Make it yours</h2><p>Manage how your name appears across your workspace.</p></div></header><form onSubmit={e=>{e.preventDefault();void run('profile',async()=>{const trimmed=name.trim();if(trimmed.length<2)throw Error('Enter at least 2 characters for your display name.');await updateUser({data:{full_name:trimmed}});const fresh=await getUser();if(!fresh)throw Error('Profile saved, but your session could not refresh. Please sign in again.');onUpdate(fresh);setName(fresh.name||trimmed);return 'Profile updated. Your workspace now uses your new name.'})}}><label className="field">Display name<input required minLength={2} maxLength={100} autoComplete="name" value={name} disabled={!!busy} onChange={e=>setName(e.target.value)}/><small>Use 2–100 characters.</small></label><label className="field">Account email<input value={user.email} readOnly type="email" autoComplete="email"/><small>Your sign-in email is read-only.</small></label><div className="account-form-footer"><span>{changed?'You have unsaved changes.':'Your profile is up to date.'}</span><button className="btn" disabled={!!busy||!changed||name.trim().length<2}>{busy==='profile'?<LoaderCircle className="account-spin" size={16}/>:<CheckCircle2 size={16}/>} {busy==='profile'?'Saving…':'Save changes'}</button></div></form></section></TabsContent>
   <TabsContent value="security" forceMount className="account-tab-panel"><section className="account-card"><header><span className="account-card-icon"><ShieldCheck size={21}/></span><div><h2>Keep your account secure</h2><p>Update your password and manage your current session.</p></div></header><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form);void run('password',async()=>{if(data.get('next')!==data.get('confirm'))throw Error('The new passwords do not match. Please check both fields.');await changePassword(String(data.get('current')),String(data.get('next')));form.reset();return 'Password updated successfully. Other sessions have been signed out.'})}}><fieldset disabled={!!busy}><PasswordField label="Current password" name="current"/><div className="account-password-grid"><PasswordField label="New password" name="next" minLength={12}/><PasswordField label="Confirm new password" name="confirm" minLength={12}/></div><p className="account-helper">Use 12–128 characters. Updating your password signs out your other sessions.</p><div className="account-form-footer"><span>Your password is never displayed by default.</span><button className="btn" disabled={!!busy}>{busy==='password'&&<LoaderCircle className="account-spin" size={16}/>} {busy==='password'?'Updating…':'Update password'}</button></div></fieldset></form><div className="account-session"><div><strong>Finish this session</strong><p>Sign out of this browser and return to the home page.</p></div><button className="btn outline" disabled={!!busy} onClick={()=>void run('logout',async()=>{await logout();location.assign('/')})}><LogOut size={16}/>{busy==='logout'?'Signing out…':'Sign out'}</button></div></section></TabsContent>
   <TabsContent value="preferences" forceMount className="account-tab-panel"><AccountPreferences/></TabsContent>
   <TabsContent value="privacy" forceMount className="account-tab-panel"><section className="account-card"><header><span className="account-card-icon"><Database size={21}/></span><div><h2>Your data, your control</h2><p>Download your account information or manage deletion.</p></div></header><div className="account-data-block"><Download size={24}/><div><h3>Take a copy of your workspace</h3><p>Export saved properties, estimates, research, reports and account data as a JSON file.</p><button className="btn outline" disabled={!!busy} onClick={()=>void exportData()}>{busy==='export'?<LoaderCircle className="account-spin" size={16}/>:<Download size={16}/>} {busy==='export'?'Preparing export…':'Export my data'}</button></div></div><div className="account-danger"><h3>Delete your account</h3><p>This permanently deletes your identity, saved research, inquiries and reviews. Export anything you need first.</p><AlertDialog open={deleting} onOpenChange={open=>{if(busy==='delete')return;setDeleting(open);if(!open){setDeletePassword('');setConfirmation('')}}}><AlertDialogTrigger asChild><button className="btn danger" disabled={!!busy}><Trash2 size={16}/>Delete account</button></AlertDialogTrigger><AlertDialogContent className="account-delete-dialog"><AlertDialogTitle>Permanently delete your account?</AlertDialogTitle><AlertDialogDescription>This cannot be undone. Confirm your password and type DELETE to remove your account and its saved information.</AlertDialogDescription><form ref={deleteForm} onSubmit={e=>{e.preventDefault();if(confirmation!=='DELETE')return;void run('delete',async()=>{await deleteAccount(deletePassword);location.assign('/')})}}><label className="field">Current password<input type="password" required autoComplete="current-password" value={deletePassword} disabled={busy==='delete'} onChange={e=>setDeletePassword(e.target.value)}/></label><label className="field">Type DELETE<input required pattern="DELETE" value={confirmation} disabled={busy==='delete'} onChange={e=>setConfirmation(e.target.value)}/></label>{feedback?.kind==='error'&&<p role="alert" className="error">{feedback.message}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy==='delete'}>Keep my account</AlertDialogCancel><button className="btn danger" type="submit" disabled={busy==='delete'||confirmation!=='DELETE'||!deletePassword}>{busy==='delete'?'Deleting…':'Permanently delete'}</button></AlertDialogFooter></form></AlertDialogContent></AlertDialog></div></section></TabsContent>
  </Tabs><aside className="account-aside"><section className="account-research"><p className="account-eyebrow">PICK UP WHERE YOU LEFT OFF</p><h2>Your research, together.</h2><p>Jump into the work you have saved.</p>{[['/dashboard','Saved research','Estimates, searches & comparisons',Bookmark],['/portfolio','Property portfolio','Manage your saved properties',FolderOpen],['/reports','Report library','Download your saved reports',FileText]].map(([href,title,description,Icon])=>{const Glyph=Icon as typeof Bookmark;return <Link key={String(href)} href={String(href)}><Glyph size={19}/><span><strong>{String(title)}</strong><small>{String(description)}</small></span><ArrowUpRight size={16}/></Link>})}</section><div className="account-privacy-note"><ShieldCheck size={23}/><h3>Built around your account</h3><p>Your saved research is tied to your signed-in account.</p><Link href="/privacy">Read our privacy information <ArrowUpRight size={14}/></Link></div></aside></div>
 </div>;
}
