'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Bell,CheckCircle2,LoaderCircle} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {api} from '../lib/api-client';
type Preferences={productUpdates:boolean;researchReminders:boolean};
export function AccountPreferences(){
 const [value,setValue]=useState<Preferences>({productUpdates:false,researchReminders:false}),[saved,setSaved]=useState<Preferences|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[error,setError]=useState('');
 const mounted=useRef(true),lock=useRef(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const result=await api<Preferences>('/api/preferences');if(mounted.current){setValue(result);setSaved(result)}}catch(e){if(mounted.current)setError((e as Error).message)}finally{if(mounted.current)setLoading(false)}},[]);
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false}},[load]);
 const changed=!!saved&&(saved.productUpdates!==value.productUpdates||saved.researchReminders!==value.researchReminders);
 return <section className="account-card"><header><span className="account-card-icon"><Bell size={21}/></span><div><h2>Set your preferences</h2><p>Choose the updates you would like to receive.</p></div></header><div className="account-preference-info">Email notifications are not currently enabled. Your choices are saved to your account.</div>{loading?<div className="account-preference-loading" role="status"><LoaderCircle className="account-spin" size={18}/>Loading your preferences…</div>:<form onSubmit={async e=>{e.preventDefault();if(lock.current||!saved||!changed)return;lock.current=true;setBusy(true);setError('');setNote('');try{const result=await api<Preferences>('/api/preferences',{method:'PATCH',body:JSON.stringify(value)});if(mounted.current){setSaved(result);setValue(result);setNote('Your preferences have been saved.')}}catch(e){if(mounted.current)setError((e as Error).message)}finally{lock.current=false;if(mounted.current)setBusy(false)}}}>{([['productUpdates','Product updates','News about features and improvements to VortexPlots.'],['researchReminders','Research reminders','Reminders to revisit your saved property research.']] as const).map(([key,title,description])=><div className="account-preference-row" key={key}><label htmlFor={'pref-'+key}><strong>{title}</strong><span>{description}</span></label><Switch id={'pref-'+key} checked={value[key]} disabled={!saved||busy} onCheckedChange={checked=>{setValue(v=>({...v,[key]:checked}));setNote('')}}/></div>)}<div className="account-form-footer"><span>{changed?'You have unsaved preferences.':'Your saved choices appear above.'}</span><button className="btn" disabled={busy||!changed}>{busy?<LoaderCircle className="account-spin" size={16}/>:<CheckCircle2 size={16}/>} {busy?'Saving…':'Save preferences'}</button></div></form>}{error&&<div className="account-feedback error" role="alert"><span>{error}</span>{!saved&&<button type="button" className="btn outline" disabled={loading} onClick={()=>void load()}>Retry</button>}</div>}{note&&<p className="account-feedback success" role="status"><CheckCircle2 size={17}/>{note}</p>}</section>;
}
