'use client';
import {useState} from 'react';
import {Download,ArrowRight,Layers,Calculator} from 'lucide-react';
import {areaMetrics,money} from './data';
export function AreaTools(){
 const [carpet,setCarpet]=useState(800),[built,setBuilt]=useState(960),[superArea,setSuper]=useState(1200),[rate,setRate]=useState(6000),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 let result:ReturnType<typeof areaMetrics>|null=null,error='';try{result=areaMetrics({carpet,built,superArea,rate})}catch(e){error=(e as Error).message}
 async function download(){setBusy(true);try{const r=await fetch('/api/public-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'efficiency',areas:{carpet,built,superArea,rate}})});if(!r.ok){const problem=await r.json() as {error?:string};throw Error(problem.error||'Could not generate PDF. Try again.');}const u=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=u;a.download='vortexplots-space-efficiency.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),5000);setStatus('Your report is ready.')}catch(e){setStatus((e as Error).message)}finally{setBusy(false)}}
 return <><p className="page-intro">See how the area you pay for compares with the space you can use.</p><div className="estimator-grid"><section className="panel"><div className="section-title"><h2>Property area breakdown</h2><Layers size={21}/></div><span className="status">Editable example · not market evidence</span><div className="form-grid">{([['Carpet area (sq ft)',carpet,setCarpet],['Built-up area (sq ft)',built,setBuilt],['Super built-up area (sq ft)',superArea,setSuper],['Quoted rate (₹/sq ft, super built-up)',rate,setRate]] as const).map(([label,value,setter])=><label className="field" key={label}>{label}<input type="number" min="1" step="any" value={Number.isNaN(value)?'':value} onChange={e=>setter(e.target.value===''?NaN:Number(e.target.value))}/></label>)}</div>{error&&<p role="alert" className="error">{error}</p>}<div className="coverage-note"><Calculator size={19}/><p>Use areas from the same property document. No locality price is assumed.</p></div><button className="btn" onClick={download} disabled={!result||busy}><Download size={17}/>{busy?'Preparing PDF…':'Download efficiency report'}</button>{status&&<p role="status">{status}</p>}</section><section className="result-panel"><p className="eyebrow">YOUR USABLE SPACE</p><h2>What you really get.</h2><strong className="value">{result?result.efficiency.toFixed(1)+'%':'—'}</strong><p>Carpet area / super built-up area</p><div className="efficiency-bar"><span style={{width:(result?.efficiency||0)+'%'}}/></div><dl><div><dt>Loading factor</dt><dd>{result?result.loading.toFixed(1)+'%':'—'}</dd></div><div><dt>Wall & other built-up area</dt><dd>{result?result.wallArea.toLocaleString('en-IN')+' sq ft':'—'}</dd></div><div><dt>Common-area allocation</dt><dd>{result?result.commonArea.toLocaleString('en-IN')+' sq ft':'—'}</dd></div><div><dt>Scenario purchase value</dt><dd>{money(result?.total??null)}</dd></div><div><dt>True usable cost / carpet sq ft</dt><dd>{money(result?.usableCost??null)}</dd></div><div><dt>Quoted rate / sq metre</dt><dd>{money(result?.rateSqm??null)}</dd></div></dl></section></div><div className="panel section"><h2>Follow the calculation</h2><div className="formula-grid"><div><b>Loading factor</b><p>(Super built-up − carpet) ÷ carpet × 100</p></div><div><b>Space efficiency</b><p>Carpet ÷ super built-up × 100</p></div><div><b>True usable cost</b><p>(Rate × super built-up) ÷ carpet</p></div><div><b>Rate normalization</b><p>₹/sq m = ₹/sq ft × 10.76391041671</p></div></div><p className="footnote">Loading is measured against carpet area; it is not the percentage of super built-up area occupied by shared space. Definitions in your agreement may differ. This tool does not certify RERA area measurements.</p></div></>;
}
