'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as LeafletMap,GeoJSON as GeoLayer} from 'leaflet';
import {districts} from './data';
import {Switch} from '@/components/ui/switch';
import {RotateCcw,Maximize2} from 'lucide-react';
import 'leaflet/dist/leaflet.css';
const aliases:Record<string,string>={Kanchipuram:'Kancheepuram',Thiruvallur:'Tiruvallur',Thiruvarur:'Tiruvarur',Tuticorin:'Thoothukudi',Villupuram:'Viluppuram'};
export function AtlasMap({districtId,onSelect}:{districtId:string;onSelect:(id:string)=>void}){
 const container=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),geo=useRef<GeoLayer|null>(null),handler=useRef(onSelect),selected=useRef(districtId);
 const [error,setError]=useState(''),[loaded,setLoaded]=useState(false),[missing,setMissing]=useState(true),[retry,setRetry]=useState(0);
 handler.current=onSelect;selected.current=districtId;
 useEffect(()=>{let cancelled=false;const abort=new AbortController();(async()=>{try{const L=await import('leaflet');const res=await fetch('/maps/tamil-nadu.geojson',{signal:abort.signal});if(!res.ok)throw Error('District boundaries could not load.');const data=await res.json() as GeoJSON.GeoJsonObject;if(cancelled||!container.current)return;const m=L.map(container.current,{scrollWheelZoom:false,attributionControl:true}).setView([10.9,78.5],6);map.current=m;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(m).on('tileerror',()=>setError('Base map unavailable. District boundaries remain usable.'));const g=L.geoJSON(data,{style:f=>({color:'#f9fffb',weight:1.5,fillColor:districts.find(d=>d.name===(aliases[f?.properties.name]||f?.properties.name))?.id===selected.current?'#b8ef71':'#388b86',fillOpacity:.68}),onEachFeature:(f,layer)=>{const name=aliases[f.properties.name]||f.properties.name,d=districts.find(d=>d.name===name);layer.bindTooltip(name,{sticky:true});if(d)layer.on('click',()=>handler.current(d.id));}}).addTo(m);geo.current=g;m.fitBounds(g.getBounds(),{padding:[14,14]});setLoaded(true);}catch(e){if(!cancelled)setError((e as Error).message)}})();return()=>{cancelled=true;abort.abort();map.current?.remove();map.current=null;geo.current=null}},[retry]);
 useEffect(()=>{geo.current?.setStyle(f=>({color:'#f9fffb',weight:1.5,fillColor:districts.find(d=>d.name===(aliases[f?.properties.name]||f?.properties.name))?.id===districtId?'#b8ef71':missing?'#388b86':'#b5c6c7',fillOpacity:missing?.68:.3}))},[districtId,missing,loaded]);
 function zoom(){geo.current?.eachLayer(l=>{const layer=l as GeoLayer;const feature=(l as unknown as {feature:{properties:{name:string}}}).feature;const d=districts.find(d=>d.name===(aliases[feature.properties.name]||feature.properties.name));if(d?.id===districtId)map.current?.fitBounds(layer.getBounds(),{padding:[24,24],maxZoom:10})})}
 return <><div className="atlas-canvas"><div ref={container} className="leaflet-host" aria-label="Interactive Tamil Nadu district map"/>{!loaded&&!error&&<div className="map-loading">Loading district boundaries…</div>}<div className="map-controls"><button className="btn outline small" onClick={zoom} disabled={!loaded}><Maximize2 size={15}/>Zoom to district</button><button aria-label="Reset map" className="btn outline small" onClick={()=>{if(geo.current)map.current?.fitBounds(geo.current.getBounds())}}><RotateCcw size={15}/></button></div><div className="map-legend"><span className="legend-key"/> No verified prices <span className="legend-key selected"/>Selected district</div></div><div className="map-bottom"><label className="switch-label"><Switch checked={missing} onCheckedChange={setMissing} aria-label="Show missing-price coverage"/>Missing-price coverage</label><span>Reference boundaries · mixed vintages to 2022</span></div>{error&&<div role="status" className="notice">{error} {!loaded&&<button onClick={()=>{setError('');setRetry(n=>n+1)}}>Retry map</button>}</div>}<p className="map-attribution">Boundary source: <a href="https://github.com/datta07/INDIAN-SHAPEFILES" target="_blank" rel="noreferrer">Indian Shapefiles (MIT)</a>. General reference, not a cadastral or certified boundary survey. Price heatmaps require verified observations.</p></>;
}
