'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Landmark,Check,Eye,EyeOff} from 'lucide-react';
import {getSettings,getUser,login,signup,requestPasswordRecovery,resendVerification,updateUser} from '../lib/auth-client';
export const authPaths=['/sign-in','/register','/forgot-password','/reset-password','/verify-email'];
export function AuthPanel({path}:{path:string}){
 const [busy,setBusy]=useState(false),[available,setAvailable]=useState(false),[mailEnabled,setMailEnabled]=useState(false),[ready,setReady]=useState(false),[visible,setVisible]=useState(false),[note,setNote]=useState(''),[returnTo,setReturnTo]=useState('/dashboard');
 useEffect(()=>{const p=new URLSearchParams(location.search),target=p.get('returnTo');if(target&&target.startsWith('/')&&!target.startsWith('//')&&!target.includes('\\')&&!authPaths.some(x=>target.split('?')[0]===x))setReturnTo(target);if(p.get('passwordUpdated')==='1')setNote('Password updated successfully. Sign in with your new password.');if(p.get('verified')==='1')setNote('Email verified successfully. You can now sign in.');if(p.get('error'))setNote('The link is invalid or expired. Request a new email.');getSettings().then(s=>{setAvailable(s.available);setMailEnabled(s.recoveryAvailable);if(['/forgot-password','/verify-email'].includes(path)&&!s.recoveryAvailable)setNote('Email delivery is not configured on this host. Password recovery and verification emails are currently unavailable.')}).catch(()=>setNote('Account service is temporarily unavailable. Please retry shortly.')).finally(()=>setReady(true))},[path]);
 const register=path==='/register',recover=path==='/forgot-password',reset=path==='/reset-password',verify=path==='/verify-email';
 const title=register?'Create your workspace':recover?'Recover your password':reset?'Set a new password':verify?'Check your email':'Welcome back';
 return <section className="auth-layout"><div className="auth-intro"><Landmark size={48}/><p className="eyebrow">TAMIL NADU PROPERTY INTELLIGENCE</p><h1>Your next move.<br/>Grounded in evidence.</h1><p>One private workspace for your locations, property analysis and reports.</p><ul><li><Check/>38 district boundaries</li><li><Check/>Traceable prices and honest data gaps</li><li><Check/>Your portfolio, securely saved</li></ul></div><form key={path} className="panel auth-form" onSubmit={async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget),email=String(f.get('email')||''),password=String(f.get('password')||'');setBusy(true);setNote('');try{
 if(verify){await resendVerification(email);setNote('If this address needs verification, check your email for a new link.');return;}
 if(recover){await requestPasswordRecovery(email);setNote('If an account exists for this address, a recovery link will arrive by email.');return;}
 if(reset){if(password!==f.get('confirm'))throw Error('New passwords must match.');await updateUser({password});location.assign('/sign-in?passwordUpdated=1');return;}
 if(register){if(password!==f.get('confirm'))throw Error('Passwords must match.');await signup(email,password,{full_name:String(f.get('name')).trim()});if(!await getUser()){location.assign('/verify-email');return;}}
 else await login(email,password);
 location.assign(returnTo+(register?(returnTo.includes('?')?'&':'?')+'welcome=1':''));
 }catch(error){setNote((error as Error).message)}finally{setBusy(false)}}}><p className="eyebrow">YOUR VORTEXPLOTS ACCOUNT</p><h2>{title}</h2>{note&&<p className="notice" role="status">{note}</p>}<>{verify&&<p>Follow the email verification link before signing in. Enter your address below to request another link.</p>}{register&&<label className="field">Display name<input name="name" required minLength={2} maxLength={100} autoComplete="name"/></label>}{!reset&&<label className="field">Email address<input name="email" type="email" required autoComplete="email" maxLength={254}/></label>}{!recover&&!verify&&<><label className="field">Password<div className="password-control"><input name="password" type={visible?'text':'password'} required minLength={register||reset?12:1} maxLength={128} autoComplete={register||reset?'new-password':'current-password'}/><button type="button" className="icon-btn" aria-label={visible?'Hide password':'Show password'} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}>{visible?<EyeOff size={20}/>:<Eye size={20}/>}</button></div></label>{(register||reset)&&<label className="field">Confirm password<input name="confirm" type={visible?'text':'password'} required minLength={12} maxLength={128} autoComplete="new-password"/></label>}</>}<button disabled={!ready||!available||busy||((recover||verify)&&!mailEnabled)} className="btn full">{busy?'Please wait…':!ready?'Connecting…':verify?'Resend verification email':register?'Create account':recover?'Send recovery link':reset?'Save new password':'Sign in'}</button></><div className="auth-links"><Link href={'/sign-in?returnTo='+encodeURIComponent(returnTo)}>Sign in</Link><Link href={'/register?returnTo='+encodeURIComponent(returnTo)}>Create account</Link><Link href="/forgot-password">Forgot password?</Link><Link href="/verify-email">Verify email</Link></div><p className="footnote">By continuing, you agree to our <Link href="/terms">terms</Link> and <Link href="/privacy">privacy information</Link>.</p></form></section>;
}
