'use client';
import {useState,type ReactNode} from 'react';
import Link from 'next/link';
import {MapPin,House,Ruler,ArrowRight,ArrowUpRight,Download,Save,ShieldCheck,SlidersHorizontal,ScanLine} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {districts,localities,propertyTypes,allowedBases,isLand,units,money,calculate,type Inputs,type Result} from './data';
import {CalculationDetails} from './rate-summary';
import {ModelPanel} from './model-panel';
import './estimator-dashboard.css';

function Picker({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){
 return <div className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>;
}
function PlacePicker({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){
 return <div className="field"><span>{label}</span><Combobox items={options} value={value} onValueChange={v=>{if(v)onChange(v)}}><ComboboxInput aria-label={label} placeholder={'Find '+label.toLowerCase()} /><ComboboxContent><ComboboxEmpty>No matching places.</ComboboxEmpty><ComboboxList>{(item:string)=><ComboboxItem key={item} value={item}>{item}</ComboboxItem>}</ComboboxList></ComboboxContent></Combobox></div>;
}
function Step({id,number,title,description,icon,children}:{id:string;number:string;title:string;description:string;icon:ReactNode;children:ReactNode}){
 return <section className="estimate-step" id={id}><header><span className="estimate-step-number">{number}</span><div><h2>{title}</h2><p>{description}</p></div>{icon}</header>{children}</section>;
}
export function EstimatorDashboard({input,set,result,busy,onSave,onDownload}:{input:Inputs;set:(patch:Partial<Inputs>)=>void;result:Result|null;busy:boolean;onSave:()=>void;onDownload:()=>void}){
 const locality=localities.find(l=>l.id===input.localityId)!,district=districts.find(d=>d.id===locality.districtId)!;
 const [scenario,setScenario]=useState(false);
 const mode=input.manualRate!==undefined||scenario?'scenario':input.useModel?'model':'sample';
 const error=(()=>{try{calculate(input);return ''}catch(e){return (e as Error).message}})();
 const available=!!result&&result.rate!==null;
 const changeProperty=(value:string)=>{setScenario(false);set({propertyType:value,basis:isLand(value)?'Plot area':'Built-up area',manualRate:undefined})};
 const changeMode=(value:string)=>{setScenario(value==='scenario');set({useModel:value==='model',manualRate:undefined})};
 const pendingScenario=mode==='scenario'&&input.manualRate===undefined;
 const shown=available&&!pendingScenario;
 return <div className="estimate-studio">
  <section className="estimate-intro"><div><span className="estimate-kicker"><ScanLine size={15}/> PROPERTY ANALYSIS STUDIO</span><h2>A clearer picture of<br/><em>your next property.</em></h2><p>Choose a place. Define the space. Understand the price.</p></div><div className="estimate-intro-note"><ShieldCheck size={24}/><strong>Evidence before estimates</strong><p>Source-linked prices. Explicit assumptions. No hidden premiums.</p><Link href="/data-health">Explore data coverage <ArrowUpRight size={15}/></Link></div></section>
  <nav className="estimate-path" aria-label="Estimator sections"><a href="#estimate-location"><span>01</span>Location</a><ArrowRight size={16}/><a href="#estimate-property"><span>02</span>Property & area</a><ArrowRight size={16}/><a href="#estimate-method"><span>03</span>Pricing method</a><a href="#estimate-result" className="estimate-result-link">View result <ArrowUpRight size={15}/></a></nav>
  <div className="estimate-layout"><div className="estimate-inputs">
   <Step id="estimate-location" number="01" title="Start with the location" description="Search within all 38 Tamil Nadu districts." icon={<MapPin size={21}/>}>
    <div className="form-grid"><PlacePicker label="District" value={district.name} options={districts.map(d=>d.name)} onChange={name=>{const id=districts.find(d=>d.name===name)!.id;setScenario(false);set({localityId:localities.find(l=>l.districtId===id)!.id,manualRate:undefined})}}/><PlacePicker key={district.id} label="Locality" value={locality.name} options={localities.filter(l=>l.districtId===district.id).map(l=>l.name)} onChange={name=>{setScenario(false);set({localityId:localities.find(l=>l.districtId===district.id&&l.name===name)!.id,manualRate:undefined})}}/></div>
    <div className="estimate-location-caption"><MapPin size={15}/><span>{locality.name}, {district.name}</span><Link href={'/locations/'+district.id}>District insights <ArrowUpRight size={14}/></Link></div>
   </Step>
   <Step id="estimate-property" number="02" title="Define your property" description="Keep the area and the quoted price basis consistent." icon={<House size={21}/>}>
    <div className="form-grid"><Picker label="Property type" value={input.propertyType} options={propertyTypes} onChange={changeProperty}/><Picker label="Quoted area basis" value={input.basis} options={allowedBases(input.propertyType)} onChange={basis=>{setScenario(false);set({basis,manualRate:undefined})}}/></div>
    <div className="estimate-area"><label className="field" htmlFor="estimate-area-value">{isLand(input.propertyType)?'Land area':'Property area'}<input id="estimate-area-value" type="number" inputMode="decimal" min="0.01" step="any" aria-invalid={!!error} aria-describedby="estimate-area-help" value={Number.isFinite(input.area)?input.area:''} onChange={e=>set({area:e.target.value===''?NaN:Number(e.target.value)})}/></label><Picker label="Area unit" value={input.unit} options={Object.keys(units)} onChange={unit=>set({unit})}/></div>
    <p id="estimate-area-help" className="estimate-help"><Ruler size={16}/>{Number.isFinite(input.area)&&input.area>0?(input.area*units[input.unit]).toLocaleString('en-IN',{maximumFractionDigits:2})+' sq ft':'Enter a positive area'} · {input.basis}</p>
    <details className="estimate-explainer"><summary>Which area should I use?</summary><p>Carpet is usable internal floor area. Built-up includes walls and covered spaces. Super built-up also includes a share of common areas. Land uses plot area.</p><Link href="/area-tools">Compare area efficiency →</Link></details>
   </Step>
   <Step id="estimate-method" number="03" title="Choose your pricing approach" description="The method is always shown with your result." icon={<SlidersHorizontal size={21}/>}>
    <RadioGroup className="estimate-modes" aria-label="Pricing approach" value={mode} onValueChange={changeMode}>{[['sample','Source sample','Use compatible observed prices.'],['model','Ridge model','Experimental district asking estimate.'],['scenario','Your scenario','Test your own researched rate.']].map(([value,title,description])=><label key={value} className={'estimate-mode '+(mode===value?'active':'')}><RadioGroupItem value={value} disabled={value==='model'&&input.category!=='asking'}/><span><strong>{title}</strong><small>{description}</small></span></label>)}</RadioGroup>
    {mode==='scenario'?<div className="estimate-method-body"><label className="field">Your rate (₹ / sq ft)<input type="number" inputMode="decimal" min="0.01" step="any" placeholder="Enter your researched rate" value={input.manualRate??''} onChange={e=>set({manualRate:e.target.value===''?undefined:Number(e.target.value),useModel:false})}/></label><p className="estimate-help">A personal planning scenario, not a verified market or official guideline value.</p></div>:<div className="estimate-method-body"><div className="form-grid"><div className="field"><span>Price data category</span><Select value={input.category} onValueChange={category=>set({category,useModel:category==='asking'&&input.useModel,manualRate:undefined})}><SelectTrigger className="choice" aria-label="Price data category"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="asking">Advertised asking prices</SelectItem><SelectItem value="transaction">Recorded transactions</SelectItem><SelectItem value="guideline">Official guideline values</SelectItem></SelectContent></Select></div>{mode==='sample'&&<div className="field"><span>Sample geography</span><Select value={input.priceScope||'locality'} onValueChange={priceScope=>set({priceScope:priceScope as 'locality'|'district'})}><SelectTrigger className="choice" aria-label="Sample geography"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="locality">Exact locality</SelectItem><SelectItem value="district">District approximation</SelectItem></SelectContent></Select></div>}</div><p className="estimate-help">{mode==='model'?'Predicts asking rates from district, property type, area basis and area. It can abstain where data is insufficient.':input.priceScope==='district'?'District samples are approximations, not verified prices for your selected locality.':'Only compatible records from your selected locality are used. No nearby rate is substituted.'}</p></div>}
   </Step>
  </div><aside className="estimate-output" id="estimate-result" aria-label="Property estimate">
   <div className="estimate-value-card"><div className="estimate-value-top"><span className="estimate-kicker">YOUR PROPERTY SNAPSHOT</span><span className="estimate-live">Updates as you edit</span></div><p className="estimate-address">{locality.name}<span>{district.name} · {input.propertyType}</span></p><div aria-live="polite" aria-atomic="true"><h2>{mode==='scenario'?'Planning scenario':mode==='model'?'Model estimate':'Estimated property value'}</h2><strong className="estimate-total">{shown?money(result!.total):'—'}</strong><p>{shown?money(result!.rate)+' / sq ft × '+result!.areaSqft.toLocaleString('en-IN',{maximumFractionDigits:2})+' sq ft':pendingScenario?'Enter a rate to build your scenario.':error?'Check the highlighted inputs.':'No compatible price available for this selection.'}</p></div><span className="estimate-method-tag">{mode==='scenario'?'User-entered · unverified':mode==='model'?'Experimental model · low confidence':'Observed asking / source sample · low confidence'}</span>
    {shown&&result?.range&&<div className="estimate-range"><span>Observed total price range</span><strong>{money(result.range[0]*result.areaSqft)} – {money(result.range[1]*result.areaSqft)}</strong><small>Source range, not a statistical confidence interval.</small></div>}
    <div className="estimate-facts"><div><span>Area basis</span><strong>{input.basis}</strong></div><div><span>Source records</span><strong>{result?.evidence.length??0}</strong></div><div><span>Latest source / collection date</span><strong>{result?.summary?.updated||'Not available'}</strong></div></div>
   </div>
   <div className="estimate-action-card">{error&&<p className="error" role="alert">{error}</p>}<button className="btn full" disabled={busy||!shown} onClick={onSave}><Save size={17}/>{busy?'Working…':'Save this analysis'}</button><button className="btn outline full" disabled={busy||!result||pendingScenario} onClick={onDownload}><Download size={17}/>Download PDF report</button><p>Saved to your private workspace. Reports preserve the selected inputs and sources.</p>{!shown&&!error&&!pendingScenario&&<Link href={'/locations/'+district.id}>Explore available district data <ArrowUpRight size={15}/></Link>}</div>
   <div className="estimate-note"><ShieldCheck size={20}/><p>Taxes, registration, financing and unsupported property premiums are excluded. Asking prices are not completed-sale prices.</p></div>
  </aside></div>
  <details className="estimate-evidence" open><summary>Calculation, sources & assumptions <span>Inspect the numbers behind your result</span></summary>{result&&!pendingScenario?<CalculationDetails result={result}/>:<p>Complete the area and pricing inputs to inspect the calculation.</p>}</details>
  <details className="estimate-evidence"><summary>Model validation & limitations <span>Measured performance of the experimental Ridge model</span></summary><ModelPanel/></details>
 </div>;
}
