'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {api} from '../lib/api-client';
import {ResearchDashboard} from './research-panels';
import {AtlasMap} from './atlas-map';
import {currentPrices,districts,localities,datasetVersion,priceDate,money,type Inputs} from './data';
type Row={id:string;title?:string;createdAt:string;inputs?:Inputs;result?:{total:number|null;status:string}};
export function Overview({download}:{download:(body:object)=>Promise<void>}){
 const [data,setData]=useState<{user:{name:string};data:Record<string,Row[]>}|null>(null),[error,setError]=useState(''),[district,setDistrict]=useState('chennai');
 useEffect(()=>{api<typeof data>('/api/dashboard').then(setData).catch(e=>setError(e.message))},[]);
 const timeline=data?Object.entries(data.data).flatMap(([kind,rows])=>rows.map(row=>({...row,kind}))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,6):[];
 return <><section className="overview-hero"><div><p className="eyebrow">YOUR PROPERTY INTELLIGENCE WORKSPACE</p><h2>{data?'Welcome back, '+(data.user.name||'researcher'):'Welcome to your overview'}</h2><p>Continue your research with clear sources, useful comparisons and private records.</p></div><Link className="btn" href="/estimator">Start new analysis →</Link></section>{error&&<p className="notice" role="alert">{error}</p>}<div className="quick-actions section"><Link href="/locations">Search a locality →</Link><Link href="/explore">Explore the map →</Link><Link href="/price-intelligence">Compare prices →</Link>{data?.data.pdfs?.[0]?<a href={'/api/report-pdf?id='+data.data.pdfs[0].id}>Download latest PDF →</a>:<Link href="/estimator">Create your first report →</Link>}<button onClick={()=>download({type:'overview'})}>Overview PDF ↓</button></div><div className="two-col"><section className="panel"><h2>Recent activity</h2>{!data&&!error?<div className="loading-skeleton" aria-label="Loading activity"/>:timeline.length?<ol className="activity-timeline">{timeline.map(row=><li key={row.kind+row.id}><strong>{row.title||row.inputs?.label||localities.find(l=>l.id===row.inputs?.localityId)?.name||row.kind}</strong><span>{row.kind} · {new Date(row.createdAt).toLocaleDateString()}</span>{row.result&&<small>{row.result.status}: {money(row.result.total)}</small>}</li>)}</ol>:<div className="empty"><h3>Your research starts here</h3><p>Save an estimate, property or report to begin your activity timeline.</p><Link className="btn" href="/estimator">Analyze a property</Link></div>}</section><section className="panel"><h2>Data quality at a glance</h2><dl><div><dt>Administrative directory</dt><dd>{districts.length} districts</dd></div><div><dt>Source records</dt><dd>{currentPrices.length} asking observations</dd></div><div><dt>Latest collection / effective date</dt><dd>{currentPrices.map(priceDate).sort().at(-1)}</dd></div><div><dt>Dataset</dt><dd>{datasetVersion}</dd></div><div><dt>Verified transactions</dt><dd>{currentPrices.filter(r=>r.category==='transaction'&&r.verified).length}</dd></div></dl><p>Screened advertisements are not completed sales. Unknown effective dates and sparse samples limit reliability.</p><Link className="text-link" href="/data-health">Inspect coverage and gaps →</Link></section></div><ResearchDashboard/><details className="panel section"><summary>Explore Tamil Nadu · map preview</summary><AtlasMap districtId={district} onSelect={setDistrict}/></details></>;
}
