'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {Star,MessageSquare,PenLine,ShieldCheck,ThumbsUp,Flag,ChevronLeft,ChevronRight,LoaderCircle,CheckCircle2,AlertCircle,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {api} from '@/lib/api-client';
import './reviews-dashboard.css';
type Review={id:string;title:string;description:string;rating:number;category:string;displayName:string;createdAt:string;status:string;emailVerified:boolean;helpfulCount:number};
type Feed={rows:Review[];average:number|null;total:number;hasMore:boolean;distribution:{rating:number;count:number}[]};
const categories=['General','Estimator','Location atlas','Reports','Account'];
const blank={rating:0,title:'',description:'',category:'General'};
function Stars({rating}:{rating:number}){return <span className="review-stars" aria-label={rating+' out of 5 stars'}>{[1,2,3,4,5].map(n=><Star key={n} size={16} aria-hidden="true" className={n<=rating?'filled':''}/>)}</span>}
function Selector({label,value,values,onChange,disabled=false}:{label:string;value:string;values:{value:string;label:string}[];onChange:(v:string)=>void;disabled?:boolean}){return <div className="field"><span>{label}</span><Select value={value} onValueChange={onChange} disabled={disabled}><SelectTrigger className="choice" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v.value} value={v.value}>{v.label}</SelectItem>)}</SelectContent></Select></div>}
export function Reviews({signedIn}:{signedIn:boolean}){
 const [feed,setFeed]=useState<Feed|null>(null),[mine,setMine]=useState<Review|null>(null),[loading,setLoading]=useState(true),[ownLoading,setOwnLoading]=useState(true),[feedError,setFeedError]=useState(''),[ownError,setOwnError]=useState('');
 const [rating,setRating]=useState('all'),[category,setCategory]=useState('all'),[page,setPage]=useState(1),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState<{error:boolean;text:string}|null>(null);
 const [editor,setEditor]=useState(false),[draft,setDraft]=useState(blank),[report,setReport]=useState<Review|null>(null),[reason,setReason]=useState(''),[deleting,setDeleting]=useState(false),[helpful,setHelpful]=useState<string[]>([]);
 const lock=useRef(false),draftOwner=useRef<string|null>(null);
 useEffect(()=>{let active=true;setLoading(true);setFeedError('');api<Feed>('/api/reviews?'+new URLSearchParams({page:String(page),...(rating!=='all'?{rating}:{}),...(category!=='all'?{category}:{})})).then(result=>{if(active){if(!result.rows.length&&page>1){setPage(p=>p-1);return}setFeed(result)}}).catch(e=>{if(active)setFeedError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[page,rating,category,revision]);
 useEffect(()=>{let active=true;setOwnError('');if(!signedIn){setMine(null);setOwnLoading(false);return}setOwnLoading(true);api<{rows:Review[]}>('/api/reviews?mine=1').then(r=>{if(active)setMine(r.rows[0]||null)}).catch(e=>{if(active)setOwnError(e.message)}).finally(()=>{if(active)setOwnLoading(false)});return()=>{active=false}},[signedIn,revision]);
 async function act(fn:()=>Promise<string>){if(lock.current)return;lock.current=true;setBusy(true);setNotice(null);try{const text=await fn();setNotice({error:false,text});setRevision(n=>n+1)}catch(e){setNotice({error:true,text:e instanceof Error?e.message:'Please try again.'})}finally{lock.current=false;setBusy(false)}}
 function write(){setNotice(null);if(mine&&draftOwner.current!==mine.id){setDraft({rating:mine.rating,title:mine.title,description:mine.description,category:mine.category});draftOwner.current=mine.id}setEditor(true)}
 const resetFilters=()=>{setRating('all');setCategory('all');setPage(1)};
 const message=notice&&<div className={'review-feedback '+(notice.error?'error':'success')} role={notice.error?'alert':'status'}>{notice.error?<AlertCircle size={17}/>:<CheckCircle2 size={17}/>}<span>{notice.text}</span></div>;
 return <div className="reviews-studio"><section className="reviews-hero"><div><p className="reviews-eyebrow">THE VORTEXPLOTS COMMUNITY</p><h2>Every experience<br/><em>makes us better.</em></h2><p>Share what worked, what could improve, and what helped your property research.</p></div><div className="reviews-hero-action"><span><ShieldCheck size={18}/>User-submitted. Moderated before publishing.</span>{signedIn?<button className="btn" disabled={busy||ownLoading||!!ownError} onClick={write}><PenLine size={17}/>{mine?'Edit your review':'Write a review'}</button>:<Link className="btn" href="/sign-in?returnTo=%2Freviews">Sign in to review</Link>}</div></section>
 <div className="reviews-notice">{message}</div><div className="reviews-layout"><div className="reviews-main"><section className="reviews-summary" aria-label="Overall community ratings"><div className="reviews-score"><p>Overall rating</p><strong>{feed?.average==null?'—':feed.average.toFixed(1)}<small>/ 5</small></strong><Stars rating={Math.round(feed?.average||0)}/><span>{feed?feed.total+' published '+(feed.total===1?'review':'reviews'):'Loading ratings…'}</span></div><div className="reviews-distribution">{[5,4,3,2,1].map(n=>{const count=feed?.distribution.find(d=>d.rating===n)?.count||0;return <button key={n} aria-label={'Filter '+n+' star reviews'} aria-pressed={rating===String(n)} disabled={busy} onClick={()=>{setRating(rating===String(n)?'all':String(n));setPage(1)}}><span>{n}<Star size={12}/></span><progress value={count} max={feed?.total||1} aria-label={n+' star distribution'}/><small>{count}</small></button>})}<p>All published reviews · summary stays global when filtering.</p></div></section>
 <section className="reviews-feed"><header><div><h2>Community voices</h2><p>Experiences from people using VortexPlots.</p></div><span>Newest first</span></header><div className="reviews-filters"><Selector label="Rating" value={rating} onChange={v=>{setRating(v);setPage(1)}} disabled={busy} values={[{value:'all',label:'All ratings'},...[5,4,3,2,1].map(n=>({value:String(n),label:n+' stars'}))]}/><Selector label="Service" value={category} onChange={v=>{setCategory(v);setPage(1)}} disabled={busy} values={[{value:'all',label:'All services'},...categories.map(c=>({value:c,label:c}))]}/>{(rating!=='all'||category!=='all')&&<button className="text-link" disabled={busy} onClick={resetFilters}>Reset filters</button>}</div>
 <div aria-busy={loading}>{loading?<div className="reviews-loading" role="status"><LoaderCircle className="reviews-spin" size={20}/><span>Loading community reviews…</span></div>:feedError?<div className="reviews-empty" role="alert"><AlertCircle/><h3>Reviews could not load</h3><p>{feedError}</p><button className="btn outline" onClick={()=>setRevision(n=>n+1)}>Try again</button></div>:feed?.rows.length?feed.rows.map(r=><article className="review-card" key={r.id}><header><div className="review-avatar" aria-hidden="true">{r.displayName?.trim().slice(0,1).toUpperCase()||'U'}</div><div className="review-author"><strong>{r.displayName||'Community member'}</strong><time dateTime={r.createdAt}>{new Date(r.createdAt).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</time></div>{r.emailVerified&&<span className="review-verified"><ShieldCheck size={13}/>Email verified</span>}</header><div className="review-card-meta"><Stars rating={r.rating}/><span>{r.category}</span></div><h3>{r.title}</h3><p className="review-copy">{r.description}</p><footer><small>User-submitted review</small>{signedIn&&mine?.id!==r.id&&<div><button disabled={busy||ownLoading||!!ownError||helpful.includes(r.id)} aria-pressed={helpful.includes(r.id)} onClick={()=>void act(async()=>{const response=await api<{message:string}>('/api/reviews',{method:'PATCH',body:JSON.stringify({id:r.id,helpful:true})});setHelpful(v=>[...v,r.id]);return response.message})}><ThumbsUp size={15}/>{helpful.includes(r.id)?'Marked helpful':'Helpful'} · {r.helpfulCount}</button><button disabled={busy||ownLoading||!!ownError} aria-label={'Report review: '+r.title} onClick={()=>{setReport(r);setReason('');setNotice(null)}}><Flag size={15}/><span>Report</span></button></div>}</footer></article>):<div className="reviews-empty"><MessageSquare size={30}/><h3>{rating!=='all'||category!=='all'?'No reviews match these filters':'The conversation starts with you'}</h3><p>{rating!=='all'||category!=='all'?'Try another rating or service to see more feedback.':'There are no published reviews yet. Share your experience for moderation.'}</p>{rating!=='all'||category!=='all'?<button className="btn outline" onClick={resetFilters}>Show all reviews</button>:signedIn&&<button className="btn outline" disabled={ownLoading||!!ownError||busy} onClick={write}>{mine?'View your review':'Write a review'}</button>}</div>}</div><nav className="reviews-pagination" aria-label="Review pages"><button className="btn outline" disabled={page===1||busy||loading} onClick={()=>setPage(n=>n-1)}><ChevronLeft size={15}/>Previous</button><span>Page {page}</span><button className="btn outline" disabled={!feed?.hasMore||busy||loading||!!feedError} onClick={()=>setPage(n=>n+1)}>Next<ChevronRight size={15}/></button></nav></section></div>
 <aside className="reviews-aside"><section className="review-own"><p className="reviews-eyebrow">YOUR CONTRIBUTION</p><h2>Your perspective matters.</h2>{ownLoading?<p role="status">Loading your review…</p>:ownError?<><p role="alert">{ownError}</p><button className="btn outline" onClick={()=>setRevision(n=>n+1)}>Retry</button></>:mine?<><span className={'review-status '+mine.status}>{mine.status==='pending'?'Awaiting moderation':mine.status==='approved'?'Published':mine.status}</span><Stars rating={mine.rating}/><h3>{mine.title}</h3><p className="review-own-copy">{mine.description}</p><div className="review-own-actions"><button className="btn outline" disabled={busy} onClick={write}><PenLine size={15}/>Edit review</button><button className="review-delete" disabled={busy} aria-label="Delete your review" onClick={()=>{setDeleting(true);setNotice(null)}}><Trash2 size={17}/></button></div></>:<><p>Tell us about your experience with estimates, locations, reports or account features.</p>{signedIn?<button className="btn outline" onClick={write} disabled={busy}><PenLine size={16}/>Share your experience</button>:<Link className="btn outline" href="/sign-in?returnTo=%2Freviews">Sign in to contribute</Link>}</>}</section><section className="reviews-guidance"><ShieldCheck size={23}/><h3>A useful review helps everyone</h3><ul><li>Describe your own experience.</li><li>Be specific about the service you used.</li><li>Keep personal and property details private.</li></ul><p>New and edited reviews go through moderation before appearing publicly. Only published reviews count toward ratings.</p></section></aside></div>
 <Dialog open={editor} onOpenChange={open=>{if(!busy)setEditor(open)}}><DialogContent className="review-dialog"><DialogTitle>{mine?'Refine your review':'Share your experience'}</DialogTitle><DialogDescription>Your feedback helps improve VortexPlots. Reviews are moderated before publishing.</DialogDescription><form onSubmit={e=>{e.preventDefault();if(!draft.rating)return;const website=String(new FormData(e.currentTarget).get('website')||'');void act(async()=>{const r=await api<{message:string}>('/api/reviews',{method:mine?'PATCH':'POST',body:JSON.stringify({...draft,id:mine?.id,website})});setEditor(false);setDraft(blank);draftOwner.current=null;return r.message})}}><fieldset disabled={busy}><label className="review-rating-label">Your rating</label><RadioGroup value={String(draft.rating)} onValueChange={v=>setDraft(d=>({...d,rating:Number(v)}))} aria-label="Your star rating" className="review-rating-input">{[1,2,3,4,5].map(n=><label key={n} className={draft.rating>=n?'chosen':''}><RadioGroupItem className="sr-only" value={String(n)} aria-label={n+' stars'}/><Star size={27}/><span>{n}</span></label>)}</RadioGroup><div className="review-rating-hint">{['Choose a rating','Poor','Fair','Good','Very good','Excellent'][draft.rating]}</div><label className="field">Review title<input required minLength={3} maxLength={100} value={draft.title} placeholder="What stood out to you?" onChange={e=>setDraft(d=>({...d,title:e.target.value}))}/><small>{draft.title.length}/100 characters</small></label><label className="field">Your experience<textarea required minLength={20} maxLength={2000} rows={5} value={draft.description} placeholder="What worked well? What could we improve?" onChange={e=>setDraft(d=>({...d,description:e.target.value}))}/><small>{draft.description.length}/2,000 characters · minimum 20</small></label><Selector label="Service category" value={draft.category} onChange={category=>setDraft(d=>({...d,category}))} values={categories.map(c=>({value:c,label:c}))} disabled={busy}/><label className="honeypot" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>{notice?.error&&message}<div className="review-dialog-actions"><button type="button" className="btn outline" onClick={()=>setEditor(false)} disabled={busy}>Keep draft & close</button><button className="btn" disabled={busy||!draft.rating}>{busy?<LoaderCircle className="reviews-spin" size={16}/>:<PenLine size={16}/>} {busy?'Submitting…':mine?'Save review':'Submit for moderation'}</button></div></fieldset></form></DialogContent></Dialog>
 <Dialog open={!!report} onOpenChange={open=>{if(!busy&&!open)setReport(null)}}><DialogContent className="review-dialog"><DialogTitle>Report this review</DialogTitle><DialogDescription>Tell the moderation team what should be reviewed. Reporting does not automatically remove a review.</DialogDescription><form onSubmit={e=>{e.preventDefault();void act(async()=>{const r=await api<{message:string}>('/api/reviews',{method:'PATCH',body:JSON.stringify({id:report!.id,report:true,reason})});setReport(null);setReason('');return r.message})}}><label className="field">Reason<textarea required minLength={10} maxLength={500} rows={4} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/><small>{reason.length}/500 characters · minimum 10</small></label>{notice?.error&&message}<button className="btn" disabled={busy}>{busy?'Sending…':'Send to moderation'}</button></form></DialogContent></Dialog>
 <AlertDialog open={deleting} onOpenChange={open=>{if(!busy)setDeleting(open)}}><AlertDialogContent><AlertDialogTitle>Delete your review?</AlertDialogTitle><AlertDialogDescription>This permanently removes your review and its helpful votes. You can write a new review afterward.</AlertDialogDescription>{notice?.error&&message}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Keep review</AlertDialogCancel><button className="btn danger" disabled={busy} onClick={()=>void act(async()=>{await api('/api/reviews',{method:'DELETE',body:JSON.stringify({id:mine!.id})});setMine(null);setDraft(blank);draftOwner.current=null;setDeleting(false);return 'Your review has been deleted.'})}>{busy?'Deleting…':'Delete review'}</button></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
