'use client';
import {AuthPanel,authPaths} from './auth-panel';
import {EstimatorDashboard} from './estimator-dashboard';
import {CalculationDetails} from './rate-summary';
import {Overview} from './overview';
import {Portfolio} from './portfolio';
import './final-polish.css';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import { AtlasMap } from './atlas-map';
import {ModelPanel,RateContext} from './model-panel';
import {request} from '../lib/api-client';
import {ResearchDashboard,AccountPanel,ContactPanel,Reviews,WelcomeToast,NetworkStatus} from './research-panels';
import {MarketExplorer,Intelligence} from './market-panels';
import './research-panels.css';
import { AreaTools } from './area-tools';
import { DataHealth } from './data-health';
import {MapPinned,ArrowUpRight,ArrowRight,Search,Landmark,Building2,ChartNoAxesCombined,FolderOpen,FileText,UserRound,LayoutDashboard,LogOut,Menu,Download,Save,Plus,Trash2,Check,Info,SlidersHorizontal,Layers,ShieldCheck} from 'lucide-react';
import {getUser,getSettings,handleAuthCallback,login,signup,logout,requestPasswordRecovery,updateUser} from '@/lib/auth-client';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {districts,localities,observations,currentPrices,isLand,allowedBases,propertyTypes,units,calculate,money,slug,datasetVersion,districtSource,officialGuidelineUrl,type Inputs} from './data';
const initial:Inputs={localityId:'chennai--adyar',propertyType:'Land',area:1200,unit:'sq ft',basis:'Plot area',category:'asking'};
const nav=[['/dashboard','Overview',LayoutDashboard],['/explore','Explore map',MapPinned],['/estimator','Property estimator',Landmark],['/locations','Location atlas',MapPinned],['/price-intelligence','Price intelligence',ChartNoAxesCombined],['/portfolio','My portfolio',FolderOpen],['/reports','Reports',FileText],['/area-tools','Area & efficiency',Layers],['/data-health','Data coverage',ShieldCheck],['/account','Account',UserRound],['/reviews','Reviews',UserRound]] as const;
type User={name?:string;email:string;id:string};
type Saved={id:string;inputs:Inputs;createdAt:string;result:ReturnType<typeof calculate>};
function Choice({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(s:string)=>void}){return <div className="field"><span>{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
const opts=(items:string[])=>items.map(s=>({value:s,label:s}));
function Empty({title,children}:{title:string;children:React.ReactNode}){return <div className="empty"><Info size={24}/><h3>{title}</h3><p>{children}</p></div>}
export function Workspace({path}:{path:string}){
 const [input,setInput]=useState<Inputs>(initial),[q,setQ]=useState(''),[user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(false),[authAvailable,setAuthAvailable]=useState(false),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[menu,setMenu]=useState(false),[items,setItems]=useState<Saved[]>([]),[reportList,setReportList]=useState<{id:string;title:string;createdAt:string}[]>([]),[editId,setEditId]=useState<string|undefined>(),[reportDate,setReportDate]=useState(''),[authMode,setAuthMode]=useState(path==='/register'?'register':'login'),[compare,setCompare]=useState<string[]>([]);
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const loc=localities.find(l=>l.id===input.localityId)||localities[0],district=districts.find(d=>d.id===loc.districtId)!;
 const result=(()=>{try{return calculate(input)}catch{return null}})();
 const signedArea=!authPaths.includes(path)&&!['/about','/contact','/privacy','/terms'].includes(path);
 const set=(patch:Partial<Inputs>)=>setInput(i=>({...i,...patch}));
 const searchParams=()=>new URLSearchParams({locality:input.localityId,type:input.propertyType,area:String(input.area),basis:input.basis,unit:input.unit,category:input.category,model:input.useModel?'1':'0',scope:input.priceScope||'locality',...(input.manualRate?{rate:String(input.manualRate)}:{})}).toString();
 const signInHref=authPaths.includes(path)?'/sign-in':'/sign-in?returnTo='+encodeURIComponent(`${path}?${searchParams()}`);
 useEffect(()=>{const p=new URLSearchParams(window.location.search);let next={...initial};if(localities.some(l=>l.id===p.get('locality')))next.localityId=p.get('locality')!;if(propertyTypes.includes(p.get('type')||'')){next.propertyType=p.get('type')!;next.basis=isLand(next.propertyType)?'Plot area':'Built-up area'}if(['Carpet area','Built-up area','Super built-up area','Plot area'].includes(p.get('basis')||''))next.basis=p.get('basis')!;next.priceScope=p.get('scope')==='district'?'district':'locality';next.useModel=p.get('model')==='1';if(p.has('area'))next.area=Number(p.get('area'));if(Object.hasOwn(units,p.get('unit')||''))next.unit=p.get('unit')!;if(['asking','guideline','transaction'].includes(p.get('category')||''))next.category=p.get('category')!;if(p.has('rate'))next.manualRate=Number(p.get('rate'));setInput(next);if(p.get('reset')==='1')setAuthMode('reset');
 (async()=>{try{const callback=await handleAuthCallback();if(callback?.type==='recovery'&&path==='/sign-in'){window.location.replace('/reset-password'+window.location.search);return}const current=await getUser();setUser(current as User|null);if(current)setName(current.name||'');await getSettings();setAuthAvailable(true);}catch{setAuthAvailable(false)}finally{setAuthReady(true)}})();},[]);
 async function load(){if(!user||path!=='/reports')return;try{const [a,b]=await Promise.all([request('/api/records?kind=properties'),request('/api/report-pdf')]);if(!a.ok||!b.ok)throw Error('Saved information is temporarily unavailable. Your records have not been removed.');setItems((await a.json() as {rows:Saved[]}).rows);setReportList((await b.json() as {rows:typeof reportList}).rows)}catch(e){setNote((e as Error).message)}}
 useEffect(()=>{void load()},[user,path]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setNote('');try{await fn()}catch(e){setNote((e as Error).message||'Something went wrong. Try again.')}finally{setBusy(false)}}
 async function save(kind:string){if(!user){window.location.href=signInHref;return}await run(async()=>{const r=await request('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,inputs:input,id:kind==='properties'?editId:undefined})});const data=await r.json() as {error:string};if(!r.ok)throw Error(data.error);setNote('Saved to your account.');setEditId(undefined);await load()})}
 async function download(body:object){await run(async()=>{const r=await request(user?'/api/report-pdf':'/api/public-report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error((await r.json() as {error:string}).error);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=r.headers.get('Content-Disposition')?.match(/filename="([^"]+)"/)?.[1]||'VortexPlots_Report.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setNote(user?'PDF generated and saved to Reports.':'PDF downloaded. Sign in to store reports in your account.');await load()})}
 async function remove(id:string){await run(async()=>{const r=await request('/api/records',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'properties',id})});if(!r.ok)throw Error((await r.json() as {error:string}).error);await load()})}
 const locationRows=localities.filter(l=>`${l.name} ${l.district}`.toLowerCase().includes(q.toLowerCase()));
 const heading:Record<string,string>={'/reviews':'Community reviews','/dashboard':'Your property workspace','/estimator':'Property estimator','/locations':'Tamil Nadu, locality by locality.','/price-intelligence':'Price intelligence','/portfolio':'Your property portfolio','/reports':'Your reports','/account':'Account & privacy','/about':'Clear data. Considered decisions.','/area-tools':'Every square foot, accounted for.','/data-health':'The evidence behind the estimate.','/contact':'Talk to VortexPlots','/privacy':'Privacy information','/terms':'Terms of use'};
 useEffect(()=>{if(!authReady)return;if(!user&&signedArea)window.location.replace(signInHref)},[authReady,user,path,authMode,signedArea,signInHref]);
 const form=<div className="form-grid"><Choice label="District" value={loc.districtId} options={districts.map(d=>({value:d.id,label:d.name}))} onChange={id=>set({localityId:localities.find(l=>l.districtId===id)!.id,manualRate:undefined})}/><Choice label="Locality" value={loc.id} options={localities.filter(l=>l.districtId===loc.districtId).map(l=>({value:l.id,label:l.name}))} onChange={id=>set({localityId:id,manualRate:undefined})}/><Choice label="Property type" value={input.propertyType} options={opts(propertyTypes)} onChange={s=>set({propertyType:s,basis:isLand(s)?'Plot area':'Built-up area',manualRate:undefined})}/><Choice label="Price category" value={input.category} options={[{value:'asking',label:'Advertised asking price'},{value:'guideline',label:'Government guideline value'},{value:'transaction',label:'Recorded transaction price'}]} onChange={s=>set({category:s,manualRate:undefined})}/><Choice label="Quoted rate basis" value={input.basis} options={opts(allowedBases(input.propertyType))} onChange={basis=>set({basis,manualRate:undefined})}/><label className="field">Area ({input.basis})<input type="number" min="0.01" step="any" value={Number.isNaN(input.area)?'':input.area} onChange={e=>set({area:e.target.value===''?NaN:Number(e.target.value)})}/></label><Choice label="Area unit" value={input.unit} options={opts(Object.keys(units))} onChange={s=>set({unit:s})}/></div>;
 const priceStatus=<><span className="status amber">Verified pricing unavailable</span><p className="muted">Insufficient compatible {input.category} observations for {input.propertyType.toLowerCase()}s with {input.basis.toLowerCase()} in {loc.name}.</p><a className="text-link" href={officialGuidelineUrl} target="_blank" rel="noreferrer">Check the official guideline portal <ArrowUpRight size={15}/></a></>;
 return <div className="site"><a className="skip-link" href="#main-content">Skip to content</a><header className="top"><Link href="/" className="brand"><span className="brand-icon"><Landmark size={23}/></span><span>VortexPlots<span className="brand-sub">PROPERTY INTELLIGENCE</span></span></Link><nav className={menu?'public-nav open':'public-nav'}><Link href="/locations">Explore locations</Link><Link href="/estimator">Estimator</Link><Link href="/price-intelligence">Price intelligence</Link><Link href="/area-tools">Area tools</Link><Link href="/portfolio">Portfolio</Link><Link href="/reports">Reports</Link><Link href="/data-health">Data coverage</Link></nav><div className="top-actions">{user?<><Link href="/dashboard" className="btn outline small">My workspace</Link><button aria-label="Sign out" className="icon-btn" onClick={()=>run(async()=>{await logout();setUser(null);window.location.href='/'})}><LogOut size={19}/></button></>:<><Link href={signInHref} className="sign-link">Sign in</Link><Link href="/register" className="btn small">Create account</Link></>}<button className="mobile-menu icon-btn" aria-label="Toggle navigation" onClick={()=>setMenu(!menu)}><Menu/></button></div></header>
 {!authPaths.includes(path)&&<aside className="side"><p className="eyebrow">WORKSPACE</p>{nav.map(([href,label,Icon])=><Link href={href} key={href} className={path===href?'selected':''}><Icon size={18}/>{label}</Link>)}<div className="side-bottom"><span className="status">DATA FIRST</span><p>38 district boundaries.<br/>Transparent price coverage.</p><Link href="/about">Our methodology <ArrowUpRight size={14}/></Link></div></aside>}
 <main id="main-content" className={authPaths.includes(path)?'content wide':'content'}><WelcomeToast/><NetworkStatus/>{note&&<div role="status" className="notice">{note}</div>}
 {path==='/explore'?<><div className="command-heading"><div><p className="eyebrow">TAMIL NADU / PROPERTY INTELLIGENCE</p><h1>Find your place. <br/><span>Know your numbers.</span></h1><p>Explore the geography. Test your assumptions. Keep the evidence.</p></div><Link href="/estimator" className="btn">New valuation <ArrowUpRight size={18}/></Link></div><section className="stats"><Stat value={String(districts.length)} label="Districts in the directory"/><Stat value={String(localities.length)} label="Listed search localities"/><Stat value={String(currentPrices.length)} label="Screened asking records"/><Stat value={String(localities.filter(l=>l.districtId===loc.districtId).length)} label={`Listed localities in ${district.name}`}/></section><div className="explorer-grid"><section className="map-panel"><div className="map-title"><div><p className="eyebrow">LOCATION EXPLORER</p><h2>Tamil Nadu, in focus.</h2></div><span className="status">38 district boundaries</span></div><AtlasMap districtId={loc.districtId} onSelect={id=>set({localityId:localities.find(l=>l.districtId===id)!.id})}/></section><section className="panel research-panel"><p className="eyebrow">START AN ANALYSIS</p><h2>Where are you looking?</h2><label className="field">Find a place<input type="search" value={q} placeholder="Search Adyar, Hosur, Madurai…" onChange={e=>setQ(e.target.value)}/></label>{q&&<div className="search-results">{locationRows.slice(0,6).map(l=><button key={l.id} onClick={()=>{set({localityId:l.id,manualRate:undefined});setQ('')}}>{l.name}<small>{l.district}</small></button>)}{!locationRows.length&&<p>No listed place matches. Try its district.</p>}</div>}<Choice label="District" value={loc.districtId} options={districts.map(d=>({value:d.id,label:d.name}))} onChange={id=>set({localityId:localities.find(l=>l.districtId===id)!.id})}/><Choice label="Locality" value={loc.id} options={localities.filter(l=>l.districtId===loc.districtId).map(l=>({value:l.id,label:l.name}))} onChange={id=>set({localityId:id})}/><div className="coverage-note"><Info size={17}/><p>Inspect property-specific district asking ranges below the map. Sample prices are not verified transaction values.</p></div><Link href={'/estimator?'+searchParams()} className="btn full">Analyze {loc.name} <ArrowRight size={17}/></Link><Link href={'/locations/'+loc.districtId} className="text-link centered">Open district coverage</Link></section></div><div className="tool-ribbon"><Link href="/area-tools"><Layers/><div><b>Space efficiency</b><p>Carpet, built-up and loading factor</p></div><ArrowUpRight/></Link><Link href="/price-intelligence"><ChartNoAxesCombined/><div><b>Compare localities</b><p>Keep price categories consistent</p></div><ArrowUpRight/></Link><Link href="/data-health"><ShieldCheck/><div><b>Inspect the evidence</b><p>Sources, coverage and model readiness</p></div><ArrowUpRight/></Link></div></>:
 authPaths.includes(path)?<AuthPanel path={path}/>:
 <><div className="page-heading"><p className="eyebrow">VORTEXPLOTS / {path.split('/')[1].replaceAll('-',' ')}</p><h1>{heading[path]||'Location detail'}</h1></div>{signedArea&&!user?<Empty title={authReady?'Sign in to your workspace':'Checking your session…'}><Link className="btn" href={signInHref}>Sign in to continue <ArrowRight size={16}/></Link></Empty>:
 path==='/area-tools'?<AreaTools/>:path==='/data-health'?<DataHealth/>:path==='/estimator'?<EstimatorDashboard input={input} set={set} result={result} busy={busy} onSave={()=>void save('estimates')} onDownload={()=>void download({inputs:input})}/>:
 path.startsWith('/locations')?<MarketExplorer path={path} signedIn={!!user} download={download}/>:
 path==='/price-intelligence'?<Intelligence signedIn={!!user} download={download}/>:
 path==='/portfolio'?<Portfolio download={download}/>:
 path==='/dashboard'?<Overview download={download}/>:
 path==='/reports'?<section className="panel"><div className="toolbar"><label className="field">Find a report<input type="search" placeholder="Report name or ID" value={q} onChange={e=>setQ(e.target.value)}/></label><label className="field">Created on<input type="date" value={reportDate} onChange={e=>setReportDate(e.target.value)}/></label></div>{reportList.length?reportList.filter(r=>(r.title+' '+r.id).toLowerCase().includes(q.toLowerCase())&&(!reportDate||r.createdAt.startsWith(reportDate))).map(r=><div className="saved-row" key={r.id}><div><h3>{r.title}</h3><p>{new Date(r.createdAt).toLocaleString()} · {r.id.slice(0,8)}</p><small>Fixed snapshot · dataset and model status in PDF</small></div><div className="actions"><a href={'/api/report-pdf?id='+r.id} className="btn outline small"><Download size={16}/>PDF</a><Confirm label="Delete report" onConfirm={()=>run(async()=>{const response=await request('/api/report-pdf',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:r.id})});if(!response.ok)throw Error('Could not delete report.');await load()})}/></div></div>):<Empty title="No reports yet">Generate a PDF from an estimate, district, locality or portfolio. It will be stored as a dated snapshot.</Empty>}</section>:
 path==='/account'?user&&<AccountPanel user={user} onUpdate={setUser}/>:
 path==='/contact'?<ContactPanel user={user}/>:path==='/reviews'?<><button className="btn outline" disabled={busy} onClick={()=>download({type:'reviews'})}>Reviews PDF</button><Reviews signedIn={!!user}/></>:
 <section className="panel prose">{path==='/about'?<><h2>Property research built around traceable evidence</h2><p>VortexPlots helps people research Tamil Nadu locations, record properties and save transparent analysis reports.</p><Categories/><h3>Data and methodology</h3><p>The district directory contains 38 districts verified on 20 September 2026. The {localities.length} search localities are selected places, not a complete official administrative register. The uploaded dataset adds 628 screened advertisements across 38 districts, alongside two previously source-checked offers. Asking samples are not verified transaction prices.</p><p>The sample representative rate is (minimum + source average + maximum) ÷ 3 for one property type, area basis and price category. Exact locality evidence is the default; district samples require explicit selection. User-entered rates remain unverified scenarios. An experimental Ridge regression model is trained and evaluated against held-out asking-price records. It does not provide certified valuations, appreciation forecasts or calibrated intervals.</p><h3>Updates</h3><p>New records must include source, reuse permission, dates, property type and area basis. Invalid refreshes keep the last valid dataset. Report snapshots retain their original contents.</p><a href={districtSource} target="_blank" rel="noreferrer" className="text-link">Official district directory <ArrowUpRight size={16}/></a></>:path==='/privacy'?<><h2>What we store</h2><p>VortexPlots uses encrypted connections, password hashing and secure session cookies for sign-in. Account and saved research data are stored in PostgreSQL. Email verification and password recovery are available when email delivery is configured. VortexPlots stores the properties, estimates, PDF snapshots and inquiries that you explicitly save. Your records are accessible only after server-side authentication.</p><h3>Why we store it</h3><p>To let you return to your research and download an unchanged report. We do not collect background browsing activity.</p><h3>Access and deletion</h3><p>Export or delete saved records from Account. Delete your account directly from Account using your current password. Previously saved Sites records remain on that host until separately removed.</p></>:<><h2>Research and planning use</h2><p>Prices are presented according to their source category. A user-entered scenario is not a professional valuation. Verify property boundaries, legal title and current registration values independently.</p><h3>Coverage and reliability</h3><p>Listed places do not imply verified rates. Unsupported values remain unavailable. No investment returns or valuation accuracy are guaranteed.</p><h3>Data corrections</h3><p>Use Contact to report errors with source references. VortexPlots does not claim an official affiliation.</p></>}</section>}
 </>}
 {!authPaths.includes(path)&&<nav className="bottom-nav" aria-label="Mobile workspace"><Link href="/dashboard">Overview</Link><Link href="/estimator">Estimate</Link><Link href="/explore">Map</Link><Link href="/portfolio">Portfolio</Link><Link href="/account">Account</Link></nav>}<footer><Link href="/" className="footer-brand">VortexPlots</Link><span>Tamil Nadu property research</span><div><Link href="/about">About</Link><Link href="/contact">Contact</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></footer></main></div>
 }
function Stat({value,label}:{value:string;label:string}){return <div><strong>{value}</strong><span>{label}</span></div>}
function Categories(){return <section className="categories"><div><ShieldCheck/><h3>Government guideline</h3><p>Street or survey-specific values from the registration authority.</p></div><div><FileText/><h3>Recorded transaction</h3><p>Completed-sale observations with traceable records.</p></div><div><Building2/><h3>Advertised asking</h3><p>Seller quotations. These may differ from the final sale price.</p></div><div><ChartNoAxesCombined/><h3>Model estimate</h3><p>An experimental Ridge prediction, with held-out error metrics and explicit limitations.</p></div></section>}
function Confirm({label,onConfirm}:{label:string;onConfirm:()=>void}){return <AlertDialog><AlertDialogTrigger className="btn danger small">{label}</AlertDialogTrigger><AlertDialogContent><AlertDialogTitle>{label}?</AlertDialogTitle><AlertDialogDescription>This permanently removes the selected saved records from this account.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={onConfirm}>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}
