import assert from 'node:assert/strict';
import test from 'node:test';
import {districts,askingSamples,supplied,calculate,slug} from '../app/data.ts';
import {districtPriceGroups} from '../lib/district-prices.ts';
import {predictAskingRate,ridgeModel} from '../lib/ridge.ts';
test('browser inference matches the trained sklearn model',()=>{for(const v of ridgeModel.testVectors){const r=predictAskingRate(v.districtId,v.propertyType,v.basis,v.area);assert.ok(r);assert.ok(Math.abs(r.rate-v.expectedRate)<1e-7*Math.max(1,v.expectedRate))}});
test('all 38 districts have screened ranges without changing verification flags',()=>{assert.equal(askingSamples.length,628);for(const d of districts){assert.ok(districtPriceGroups(d.id).length>0,d.id)}assert.ok(askingSamples.every(r=>!r.verified&&!r.effectiveDate&&r.category==='asking'));});
test('training and validation locality groups are disjoint',()=>{const train=new Set(ridgeModel.trainingIds);const hold=new Set(ridgeModel.validationIds);const group=r=>r.districtId+'|'+r.locality.toLowerCase();const groups=new Set(supplied.filter(r=>train.has(r.id)).map(group));assert.ok(supplied.filter(r=>hold.has(r.id)).every(r=>!groups.has(group(r))));assert.equal(train.size+hold.size,628);assert.ok(ridgeModel.metrics.mae<ridgeModel.baselineMetrics.mae)});
test('Ridge is opt-in, does not predict guideline values, and respects support limits',()=>{const g=ridgeModel.limits.find(g=>g.count>=3&&g.propertyType==='Land');const row=supplied.find(r=>r.districtId===g.districtId&&r.propertyType===g.propertyType&&r.basis===g.basis);const input={localityId:row.districtId+'--'+slug(row.locality),propertyType:g.propertyType,basis:g.basis,area:row.area,unit:'sq ft',category:'asking'};assert.equal(calculate(input).status,'sample');assert.equal(calculate(input).modelVersion,null);const r=calculate({...input,useModel:true});assert.equal(r.status,'model');assert.ok(r.rate>0);assert.equal(r.modelVersion,ridgeModel.version);assert.equal(calculate({...input,useModel:true,category:'guideline'}).total,null);assert.equal(predictAskingRate(g.districtId,g.propertyType,g.basis,g.maxArea+1),null);assert.equal(predictAskingRate('unknown',g.propertyType,g.basis,row.area),null)});
