import {reportFilename} from '@/lib/report-naming';
import {jsonBody,limit} from '@/lib/http';
import {database} from '@/lib/database.mjs';
import {createSnapshot} from '@/lib/report-snapshot';
import {identity,store,key,list,sameOrigin,failure} from '@/lib/storage';
import {pdf,type ReportSnapshot} from '@/lib/pdf';
import {calculate,localities,districts,datasetVersion,money,officialGuidelineUrl,type Inputs} from '@/app/data';
export const runtime='nodejs';export const dynamic='force-dynamic';
export async function POST(req:Request){try{sameOrigin(req);const user=await identity();await limit('report-create',user.id,30,3600);const body=await jsonBody(req) as {type?:string;districtId?:string;localityId?:string;inputs?:Inputs};const id=crypto.randomUUID();const snapshot:ReportSnapshot={id,createdAt:new Date().toISOString(),title:'Property analysis',sections:[]};
 if(body.type==='portfolio'){snapshot.title='My Portfolio';snapshot.filename=reportFilename('MyPortfolio');const properties=await list(user.id,'properties');snapshot.sections=properties.map(p=>{const r=calculate(p.inputs);return {title:`${r.locality.name}, ${r.locality.district}`,lines:[`${r.inputs.propertyType} • ${r.areaSqft.toFixed(2)} sq ft • ${r.inputs.basis}`,`Applied rate: ${money(r.rate)} / sq ft`,`Total (${r.status}): ${money(r.total)}`,`Method: ${r.method}`,`Minimum: ${money(r.summary?.min??null)} / sq ft`,`Source average: ${money(r.summary?.average??null)} / sq ft`,`Maximum: ${money(r.summary?.max??null)} / sq ft`,`Representative: ${money(r.summary?.representative??null)} / sq ft`,`Confidence: Low. Latest date: ${r.summary?.updated||'Unavailable'}`]}});if(!properties.length)snapshot.sections.push({title:'Portfolio',lines:['No saved properties.']});}
 else if(body.type==='overview'){snapshot.title='Overview';snapshot.filename=reportFilename('Overview');for(const kind of ['properties','estimates','searches','comparisons','pdfs']){const rows=await list(user.id,kind);snapshot.sections.push({title:kind,lines:[`${rows.length} saved records`,...rows.slice(0,10).map(r=>`${r.title||r.inputs?.label||r.id} · ${r.createdAt}`)]})}}
 else if(body.type==='reviews'){snapshot.title='Reviews';snapshot.filename=reportFilename('Reviews');const published=await database().query("SELECT rating,title,description,created_at FROM reviews WHERE status='approved' ORDER BY created_at DESC LIMIT 100");snapshot.sections=published.rows.map((r:{title:string;rating:number;created_at:string;description:string})=>({title:r.title,lines:[`${r.rating} / 5 · ${new Date(r.created_at).toISOString().slice(0,10)}`,r.description,'User-submitted, moderated review.']}));if(!published.rowCount)snapshot.sections=[{title:'Community feedback',lines:['No published reviews. No rating is available.']}]}
 else{const generated=createSnapshot(body);snapshot.filename=generated.filename;snapshot.title=generated.title;snapshot.sections=generated.sections;snapshot.mapDistrict=generated.mapDistrict;}
 if(body.type==='portfolio')snapshot.sections.push({title:'Disclaimer',lines:['Analytical estimate only; not a certified valuation. Unsupported rates are excluded. Dataset: '+datasetVersion]});
 if((await list(user.id,'pdfs')).length>=200)throw Error('Report limit reached. Export or remove existing reports.');const bytes=await pdf(snapshot);await store().setJSON(key(user.id,'pdfs',id),snapshot);return new Response(new Uint8Array(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${snapshot.filename||reportFilename('Estimator',undefined,undefined,snapshot.createdAt)}"`,'Cache-Control':'private, no-store'}});
 }catch(e){return failure(e)}}
export async function GET(req:Request){try{const user=await identity();const id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({rows:await list(user.id,'pdfs')},{headers:{'Cache-Control':'private, no-store'}});const snapshot=await store().get(key(user.id,'pdfs',id),{type:'json'}) as ReportSnapshot|null;if(!snapshot)return Response.json({error:'Report not found'},{status:404});return new Response(new Uint8Array(await pdf(snapshot)),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${snapshot.filename||reportFilename('Estimator',undefined,undefined,snapshot.createdAt)}"`,'Cache-Control':'private, no-store'}})}catch(e){return failure(e)}}

export async function DELETE(req:Request){try{sameOrigin(req);const user=await identity();const body=await req.json() as {id:string};if(typeof body.id!=='string')throw Error('Choose a report.');const db=store();const k=key(user.id,'pdfs',body.id);await db.delete(k);return Response.json({ok:true})}catch(e){return failure(e)}}
