import {createSnapshot} from '@/lib/report-snapshot';
import {identity,store,key,list,sameOrigin,failure} from '@/lib/storage';
import {pdf,type ReportSnapshot} from '@/lib/pdf';
import {calculate,localities,districts,datasetVersion,money,officialGuidelineUrl,type Inputs} from '@/app/data';
export const runtime='nodejs';export const dynamic='force-dynamic';
export async function POST(req:Request){try{sameOrigin(req);const user=await identity();const body=await req.json() as {type?:string;districtId?:string;localityId?:string;inputs?:Inputs};const id=crypto.randomUUID();const snapshot:ReportSnapshot={id,createdAt:new Date().toISOString(),title:'Property analysis',sections:[]};
 if(body.type==='portfolio'){snapshot.title='Portfolio analysis';const properties=await list(user.id,'properties');snapshot.sections=properties.map(p=>{const r=calculate(p.inputs);return {title:`${r.locality.name}, ${r.locality.district}`,lines:[`${r.inputs.propertyType} • ${r.areaSqft.toFixed(2)} sq ft • ${r.inputs.basis}`,`Supported valuation: ${r.status==='observed'?money(r.total):'Unavailable'}`,`User scenario: ${r.status==='scenario'?money(r.total):'Not entered'}`]}});if(!properties.length)snapshot.sections.push({title:'Portfolio',lines:['No saved properties.']});}
 else{const generated=createSnapshot(body);snapshot.title=generated.title;snapshot.sections=generated.sections;snapshot.mapDistrict=generated.mapDistrict;}
 if(body.type==='portfolio')snapshot.sections.push({title:'Disclaimer',lines:['Analytical estimate only; not a certified valuation. Unsupported rates are excluded. Dataset: '+datasetVersion]});
 if((await list(user.id,'pdfs')).length>=200)throw Error('Report limit reached. Export or remove existing reports.');const bytes=await pdf(snapshot);await store().setJSON(key(user.id,'pdfs',id),snapshot);return new Response(new Uint8Array(bytes),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="vortexplots-${id}.pdf"`,'Cache-Control':'private, no-store'}});
 }catch(e){return failure(e)}}
export async function GET(req:Request){try{const user=await identity();const id=new URL(req.url).searchParams.get('id');if(!id)return Response.json({rows:await list(user.id,'pdfs')},{headers:{'Cache-Control':'private, no-store'}});const snapshot=await store().get(key(user.id,'pdfs',id),{type:'json'}) as ReportSnapshot|null;if(!snapshot)return Response.json({error:'Report not found'},{status:404});return new Response(new Uint8Array(await pdf(snapshot)),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="vortexplots-${id}.pdf"`,'Cache-Control':'private, no-store'}})}catch(e){return failure(e)}}

export async function DELETE(req:Request){try{sameOrigin(req);const user=await identity();const body=await req.json() as {id:string};if(typeof body.id!=='string')throw Error('Choose a report.');const db=store();const k=key(user.id,'pdfs',body.id);await db.delete(k);return Response.json({ok:true})}catch(e){return failure(e)}}
