import {z} from 'zod';
import {database} from '@/lib/database.mjs';
import {identity,sameOrigin,failure} from '@/lib/storage';
import {jsonBody,limit,PublicError} from '@/lib/http';
export const dynamic='force-dynamic';
const schema=z.object({rating:z.number().int().min(1).max(5),title:z.string().trim().min(3).max(100),description:z.string().trim().min(20).max(2000),category:z.enum(['General','Estimator','Location atlas','Reports','Account']).default('General'),website:z.string().max(0).default('')});
export async function GET(req:Request){try{const p=new URL(req.url).searchParams;const mine=p.get('mine')==='1';const page=Math.floor(Math.max(1,Math.min(10000,Number(p.get('page'))||1)));const owner=mine?(await identity()).id:null;let filter=mine?'r.owner_id=$1':"r.status='approved'";const values:(string|number|null)[]=mine?[owner]:[];
if(!mine&&p.get('rating')){values.push(z.coerce.number().int().min(1).max(5).parse(p.get('rating')));filter+=' AND r.rating=$'+values.length;}
if(!mine&&p.get('category')){values.push(z.enum(['General','Estimator','Location atlas','Reports','Account']).parse(p.get('category')));filter+=' AND r.category=$'+values.length;}const r=await database().query(`SELECT r.id,r.rating,r.title,r.description,r.category,r.status,r.created_at AS "createdAt",u.name AS "displayName",u."emailVerified" AS "emailVerified",(SELECT count(*)::int FROM review_helpful h WHERE h.review_id=r.id) AS "helpfulCount" FROM reviews r JOIN "user" u ON u.id=r.owner_id WHERE ${filter} ORDER BY r.created_at DESC LIMIT 11 OFFSET $${values.length+1}`,[...values,(page-1)*10]);const stats=await database().query("SELECT rating,count(*)::int AS count FROM reviews WHERE status='approved' GROUP BY rating");const distribution=Array.from({length:5},(_,i)=>({rating:i+1,count:stats.rows.find((v:{rating:number;count:number})=>v.rating===i+1)?.count||0}));const total=distribution.reduce((a,b)=>a+b.count,0);return Response.json({rows:r.rows.slice(0,10),page,hasMore:r.rows.length>10,total,average:total?distribution.reduce((a,b)=>a+b.rating*b.count,0)/total:null,distribution},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);const u=await identity();await limit('review-write',u.id,5);const b=schema.parse(await jsonBody(req));const id=crypto.randomUUID();const r=await database().query('INSERT INTO reviews(id,owner_id,rating,title,description,category) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(owner_id) DO NOTHING RETURNING id',[id,u.id,b.rating,b.title,b.description,b.category]);if(!r.rowCount)throw new PublicError('Edit your existing review instead.',409);return Response.json({id,status:'pending',message:'Review received for moderation.'},{status:201})}catch(e){return failure(e)}}
export async function PATCH(req:Request){try{sameOrigin(req);const u=await identity();const body=await jsonBody(req);const id=z.string().uuid().parse(body.id);if(body.helpful){await limit('review-helpful',u.id,30,3600);const target=await database().query("SELECT id FROM reviews WHERE id=$1 AND status='approved' AND owner_id<>$2",[id,u.id]);if(!target.rowCount)throw new PublicError('Review not found.',404);await database().query('INSERT INTO review_helpful(review_id,owner_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,u.id]);return Response.json({message:'Marked helpful. Each account contributes one vote.'})}await limit('review-write',u.id,5);if(body.report){const reason=z.string().trim().min(10).max(500).parse(body.reason);const target=await database().query("SELECT id FROM reviews WHERE id=$1 AND status='approved' AND owner_id<>$2",[id,u.id]);if(!target.rowCount)throw new PublicError('Review not found.',404);await database().query('INSERT INTO review_reports(review_id,owner_id,reason) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[id,u.id,reason]);return Response.json({message:'Report received for moderation.'})}const b=schema.parse(body);const r=await database().query("UPDATE reviews SET rating=$1,title=$2,description=$3,category=$4,status='pending',updated_at=now() WHERE id=$5 AND owner_id=$6 RETURNING id",[b.rating,b.title,b.description,b.category,id,u.id]);if(!r.rowCount)throw new PublicError('Review not found.',404);return Response.json({message:'Review updated and returned to moderation.'})}catch(e){return failure(e)}}
export async function DELETE(req:Request){try{sameOrigin(req);const u=await identity();const {id}=z.object({id:z.string().uuid()}).parse(await jsonBody(req));const r=await database().query('DELETE FROM reviews WHERE id=$1 AND owner_id=$2 RETURNING id',[id,u.id]);if(!r.rowCount)throw new PublicError('Review not found.',404);return Response.json({ok:true})}catch(e){return failure(e)}}
