import {reportFilename,sectionTitles,type ReportSection} from './report-naming';
import {usablePrices,summarizePrices} from './price-summary';
import {z} from 'zod';
import {currentPrices,priceDate,areaMetrics,calculate,localities,districts,datasetVersion,money,officialGuidelineUrl,type Inputs} from '@/app/data';
import type {ReportSnapshot} from './pdf';
const schema=z.object({type:z.enum(['property','efficiency','district','locality']).optional(),section:z.enum(['Estimator','PriceIntelligence','LocationAtlas','MyPortfolio','Overview','Reviews','AreaEfficiency']).optional(),propertyType:z.string().optional(),basis:z.string().optional(),category:z.enum(['asking','transaction','guideline']).optional(),days:z.number().int().min(1).max(365).optional(),checkedOnly:z.boolean().optional(),districtId:z.string().max(100).optional(),localityId:z.string().max(200).optional(),inputs:z.object({localityId:z.string(),propertyType:z.string(),area:z.number(),unit:z.string(),basis:z.string(),category:z.string(),priceScope:z.enum(['locality','district']).optional(),useModel:z.boolean().optional(),manualRate:z.number().optional()}).optional(),areas:z.object({carpet:z.number(),built:z.number(),superArea:z.number(),rate:z.number()}).optional()});
export function createSnapshot(value:unknown):ReportSnapshot{
 const b=schema.parse(value),snapshot:ReportSnapshot={id:crypto.randomUUID(),createdAt:new Date().toISOString(),title:'Estimator',sections:[]};let reportDistrict:string|undefined,reportLocality:string|undefined;
 const section:ReportSection=b.section||(b.type==='efficiency'?'AreaEfficiency':b.type==='district'||b.type==='locality'?'LocationAtlas':'Estimator');
 if(b.type==='efficiency'){
  if(!b.areas)throw Error('Enter the area measurements.');const a=areaMetrics(b.areas);snapshot.title='Space efficiency analysis';snapshot.sections=[{title:'Measurements supplied by the user',lines:[`Carpet area: ${a.carpet} sq ft`,`Built-up area: ${a.built} sq ft`,`Super built-up area: ${a.superArea} sq ft`,`Quoted rate: ${money(a.rate)} / super built-up sq ft`]}, {title:'Area efficiency and scenario value',lines:[`Loading factor: ${a.loading.toFixed(2)}%`,`Space efficiency: ${a.efficiency.toFixed(2)}%`,`Wall and other built-up area: ${a.wallArea} sq ft`,`Common-area allocation: ${a.commonArea} sq ft`,`Scenario property value: ${money(a.total)}`,`True usable cost: ${money(a.usableCost)} / carpet sq ft`,`Quoted rate: ${money(a.rateSqm)} / sq metre`]}, {title:'Calculation formulas',lines:['Loading factor = (super built-up - carpet) / carpet × 100','Space efficiency = carpet / super built-up × 100','Built-up = carpet + wall and other built-up area','Scenario value = quoted rate × super built-up area','True usable cost = scenario value / carpet area','1 sq metre = 10.76391041671 sq ft. Rate per sq metre = rate per sq ft × 10.76391041671']}];
 }else if(b.type==='district'||b.type==='locality'){
  const d=districts.find(d=>d.id===b.districtId);if(!d)throw Error('Select a district.');if(b.type==='locality'&&!b.localityId)throw Error('Select a locality.');const places=localities.filter(l=>l.districtId===d.id&&(!b.localityId||l.id===b.localityId));if(!places.length)throw Error('Locality does not belong to the selected district.');const prices=usablePrices(currentPrices.filter(o=>places.some(l=>l.id===o.localityId)&&(!b.propertyType||b.propertyType==='All'||o.propertyType===b.propertyType)&&(!b.basis||b.basis==='All'||o.basis===b.basis)&&(!b.category||o.category===b.category)&&(!b.checkedOnly||o.verified&&o.reuseApproved)&&Date.now()-Date.parse(priceDate(o))<(b.days||365)*86400000));reportDistrict=d.name;reportLocality=b.localityId?places[0].name:undefined;snapshot.mapDistrict=d.name;snapshot.title=b.type==='district'?'District coverage analysis':'Locality coverage analysis';snapshot.sections=[{title:d.name,lines:places.map(l=>`${l.name}: ${prices.filter(o=>o.localityId===l.id).length} screened asking records; administrative classification pending verification.`)},{title:'Pricing and geographic context',lines:[...prices.map(o=>`${o.propertyType} / ${o.basis} / ${o.category}: ${money(o.rate)}/sq ft. ${o.effectiveDate?'Effective '+o.effectiveDate:'Collected '+o.collectedDate+'; effective date unknown'}. ${o.sourceUrl}`),'Small samples are not locality valuations. Experimental Ridge model available; no calibrated confidence interval.','No district rate is substituted for locality evidence. Property types and area bases are kept separate.','Map source: Indian Shapefiles, MIT; mixed boundary vintages through 2022. District map snapshot is included; exact locality coordinates are not verified.','Taluk, ward, village and precise locality coordinates await authoritative verification.']}];const grouped=new Map<string,typeof prices>();for(const row of prices){const key=[row.localityId,row.propertyType,row.basis,row.category].join('|');grouped.set(key,[...(grouped.get(key)||[]),row])}for(const rows of grouped.values()){const summary=summarizePrices(rows)!;snapshot.sections.push({title:localities.find(l=>l.id===rows[0].localityId)!.name+' · '+rows[0].propertyType+' · '+rows[0].basis,lines:[`Minimum: ${money(summary.min)} / sq ft`,`Source average: ${money(summary.average)} / sq ft`,`Maximum: ${money(summary.max)} / sq ft`,`Representative: ${money(summary.representative)} / sq ft`,'Representative = (minimum + arithmetic source average + maximum) / 3',`Low confidence; ${summary.count} samples; latest source/collection date ${summary.updated}`,summary.verification]})}
 }else{
  if(!b.inputs)throw Error('Enter property inputs.');const r=calculate(b.inputs as Inputs);reportDistrict=r.locality.district;reportLocality=r.locality.name;snapshot.mapDistrict=r.locality.district;snapshot.sections=[{title:`${r.locality.name}, ${r.locality.district}`,lines:[`Property type: ${r.inputs.propertyType}`,`Area basis: ${r.inputs.basis}`,`Area: ${r.inputs.area} ${r.inputs.unit} = ${r.areaSqft.toFixed(2)} sq ft`,`Carpet / built-up / super built-up breakdown: not supplied. Use the separate efficiency report.`,`Price category: ${r.category}`,`Rate: ${money(r.rate)} per sq ft`,`Value (${r.status}): ${money(r.total)}`,`Method: ${r.method}. Model: ${r.modelVersion||'Not used'}`,`Supported rate range: ${r.range?r.range.map(n=>money(n)).join(' to '):'Unavailable'}`,`Geographic scope: ${r.scope}`,`Minimum: ${money(r.summary?.min??null)} / sq ft`,`Source average: ${money(r.summary?.average??null)} / sq ft`,`Maximum: ${money(r.summary?.max??null)} / sq ft`,`Representative: ${money(r.summary?.representative??null)} / sq ft`,`Latest source/collection date: ${r.summary?.updated||'Unavailable'}`,'Representative = (minimum + arithmetic source average + maximum) / 3',`Confidence: ${r.status==='scenario'?'Unverified user assumption':'Low; sparse asking evidence, not a verified sale'}`,`Compatible observations: ${r.evidence.length}`]},{title:'Calculation and sources',lines:[`Value = normalized area in sq ft × rate per sq ft.`,...r.evidence.map(e=>`${e.sourceName} | observation ${e.effectiveDate} | collected ${e.collectedDate} | ${e.sourceUrl}`),...(r.evidence.length?[]:['No suitable verified price observations. Source date and market price confidence are unavailable.'])]}];
 }
 snapshot.title=sectionTitles[section];snapshot.filename=reportFilename(section,reportDistrict,reportLocality,snapshot.createdAt);
 snapshot.sections.push({title:'Versions and limitations',lines:[`Dataset: ${datasetVersion}. Experimental Ridge model trained. Consult Price Intelligence for held-out validation metrics.`,`Data source for user scenarios: user-supplied measurements and rate, not verified market evidence.`,`Historical trends and prediction intervals require suitable dated observations.`,`District directory: https://igod.gov.in/sg/TN/E042/organizations`,`Guideline search: ${officialGuidelineUrl}`,'This report is an analytical estimate for research and planning, not a certified valuation. Verify measurements, legal title, boundaries and current official values independently.']});return snapshot;
}
