import {z} from 'zod';
import {areaMetrics,calculate,localities,districts,datasetVersion,money,officialGuidelineUrl,type Inputs} from '@/app/data';
import type {ReportSnapshot} from './pdf';
const schema=z.object({type:z.enum(['property','efficiency','district','locality']).optional(),districtId:z.string().max(100).optional(),localityId:z.string().max(200).optional(),inputs:z.object({localityId:z.string(),propertyType:z.string(),area:z.number(),unit:z.string(),basis:z.string(),category:z.string(),manualRate:z.number().optional()}).optional(),areas:z.object({carpet:z.number(),built:z.number(),superArea:z.number(),rate:z.number()}).optional()});
export function createSnapshot(value:unknown):ReportSnapshot{
 const b=schema.parse(value),snapshot:ReportSnapshot={id:crypto.randomUUID(),createdAt:new Date().toISOString(),title:'Property valuation scenario',sections:[]};
 if(b.type==='efficiency'){
  if(!b.areas)throw Error('Enter the area measurements.');const a=areaMetrics(b.areas);snapshot.title='Space efficiency analysis';snapshot.sections=[{title:'Measurements supplied by the user',lines:[`Carpet area: ${a.carpet} sq ft`,`Built-up area: ${a.built} sq ft`,`Super built-up area: ${a.superArea} sq ft`,`Quoted rate: ${money(a.rate)} / super built-up sq ft`]}, {title:'Area efficiency and scenario value',lines:[`Loading factor: ${a.loading.toFixed(2)}%`,`Space efficiency: ${a.efficiency.toFixed(2)}%`,`Wall and other built-up area: ${a.wallArea} sq ft`,`Common-area allocation: ${a.commonArea} sq ft`,`Scenario property value: ${money(a.total)}`,`True usable cost: ${money(a.usableCost)} / carpet sq ft`,`Quoted rate: ${money(a.rateSqm)} / sq metre`]}, {title:'Calculation formulas',lines:['Loading factor = (super built-up - carpet) / carpet × 100','Space efficiency = carpet / super built-up × 100','Built-up = carpet + wall and other built-up area','Scenario value = quoted rate × super built-up area','True usable cost = scenario value / carpet area','1 sq metre = 10.76391041671 sq ft. Rate per sq metre = rate per sq ft × 10.76391041671']}];
 }else if(b.type==='district'||b.type==='locality'){
  const d=districts.find(d=>d.id===b.districtId);if(!d)throw Error('Select a district.');if(b.type==='locality'&&!b.localityId)throw Error('Select a locality.');const places=localities.filter(l=>l.districtId===d.id&&(!b.localityId||l.id===b.localityId));if(!places.length)throw Error('Locality does not belong to the selected district.');snapshot.mapDistrict=d.name;snapshot.title=b.type==='district'?'District coverage analysis':'Locality coverage analysis';snapshot.sections=[{title:d.name,lines:places.map(l=>`${l.name}: verified locality price unavailable; administrative classification pending verification.`)},{title:'Pricing and geographic context',lines:['Minimum / median / maximum supported rate: unavailable.','District comparison rate: unavailable. No district rate is substituted for locality evidence.','Comparable localities and property-type rates: unavailable.','Map source: Indian Shapefiles, MIT; mixed boundary vintages through 2022. District map snapshot is included; exact locality coordinates are not verified.','Taluk, ward, village and precise locality coordinates await authoritative verification.']}];
 }else{
  if(!b.inputs)throw Error('Enter property inputs.');const r=calculate(b.inputs as Inputs);snapshot.mapDistrict=r.locality.district;snapshot.sections=[{title:`${r.locality.name}, ${r.locality.district}`,lines:[`Property type: ${r.inputs.propertyType}`,`Area basis: ${r.inputs.basis}`,`Area: ${r.inputs.area} ${r.inputs.unit} = ${r.areaSqft.toFixed(2)} sq ft`,`Carpet / built-up / super built-up breakdown: not supplied. Use the separate efficiency report.`,`Price category: ${r.category}`,`Rate: ${money(r.rate)} per sq ft`,`Scenario value: ${money(r.total)}`,`Supported rate range: ${r.range?r.range.map(n=>money(n)).join(' to '):'Unavailable'}`,`District comparison rate: unavailable`,`Confidence: ${r.status==='scenario'?'Unverified user assumption':'Insufficient evidence'}`,`Compatible observations: ${r.evidence.length}`]},{title:'Calculation and sources',lines:[`Value = normalized area in sq ft × rate per sq ft.`,...r.evidence.map(e=>`${e.sourceName} | observation ${e.effectiveDate} | collected ${e.collectedDate} | ${e.sourceUrl}`),...(r.evidence.length?[]:['No suitable verified price observations. Source date and market price confidence are unavailable.'])]}];
 }
 snapshot.sections.push({title:'Versions and limitations',lines:[`Dataset: ${datasetVersion}. Model: none deployed. Evaluation metrics: unavailable.`,`Data source for user scenarios: user-supplied measurements and rate, not verified market evidence.`,`Historical trends and prediction intervals require suitable dated observations.`,`District directory: https://igod.gov.in/sg/TN/E042/organizations`,`Guideline search: ${officialGuidelineUrl}`,'This report is an analytical estimate for research and planning, not a certified valuation. Verify measurements, legal title, boundaries and current official values independently.']});return snapshot;
}
