import {createHash} from 'node:crypto';
import {jsonBody,limit,PublicError} from '@/lib/http';
import {identity,store,key,list,sameOrigin,failure} from '@/lib/storage';
import {z} from 'zod';
import {calculate,validate,type Inputs} from '@/app/data';
export const dynamic='force-dynamic';
const kinds=['properties','estimates','reports','searches'];
export async function GET(req:Request){try{const user=await identity();const kind=new URL(req.url).searchParams.get('kind')||'properties';if(!kinds.includes(kind))throw new PublicError('Invalid record type');return Response.json({rows:await list(user.id,kind)},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return failure(e)}}
export async function POST(req:Request){try{sameOrigin(req);const user=await identity();await limit('records',user.id,120,3600);if(Number(req.headers.get('content-length'))>20000)throw new PublicError('Request too large');const body=z.object({kind:z.enum(['properties','estimates','reports','searches']),id:z.string().optional(),inputs:z.object({localityId:z.string(),propertyType:z.string(),area:z.number(),unit:z.string(),basis:z.string(),category:z.string(),priceScope:z.enum(['locality','district']).optional(),label:z.string().trim().min(2).max(100).optional(),carpetArea:z.number().optional(),builtArea:z.number().optional(),superArea:z.number().optional(),useModel:z.boolean().optional(),manualRate:z.number().optional(),acquisitionCost:z.number().optional(),acquisitionDate:z.string().optional()})}).parse(await jsonBody(req));if(!kinds.includes(body.kind))throw new PublicError('Invalid record type');const input=body.inputs as Inputs;validate(input);const rows=await list(user.id,body.kind);if(rows.length>=200&&!body.id&&!rows.some(r=>JSON.stringify(r.inputs)===JSON.stringify(input)))throw new PublicError('Maximum 200 records. Delete older records first.');const id=body.id||createHash('sha256').update(JSON.stringify(input)).digest('hex').slice(0,32);const k=key(user.id,body.kind,id);if(body.id&&(!await store().get(k)))return Response.json({error:'Record not found'},{status:404});if(body.id&&body.kind!=='properties')throw new PublicError('Historical records are immutable');const record={id,kind:body.kind,inputs:input,result:calculate(input),createdAt:new Date().toISOString()};await store().setJSON(k,record);return Response.json({record},{status:201});}catch(e){return failure(e)}}
export async function DELETE(req:Request){try{sameOrigin(req);const user=await identity();const {kind,id}=z.object({kind:z.string(),id:z.string()}).parse(await jsonBody(req));if(!kinds.includes(kind))throw new PublicError('Invalid record type');await store().delete(key(user.id,kind,id));return Response.json({ok:true});}catch(e){return failure(e)}}
